### ISSUE TITLE
Devblog pagination is broken

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#1]
On the [Devblog](https://godotengine.org/devblog), the pagination is broken, so only page 1 can be seen (clicking on "2" or the "next page" arrow lead to the main page).

![image](https://user-images.githubusercontent.com/4701338/30324700-44572d9e-97c2-11e7-9107-1a761b13997f.png)

It works fine on the [News](https://godotengine.org/news) page which uses the same plugin as backend.

**Comment by pcvonz** [comment]
Fixed, pageNumber wasn't set in the devblog's url.
