### ISSUE TITLE
October version 420+ will require PHP 7

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot-website#10]
We recently updated to version 419, the next version of October will upgrade to Laravel 5.5 which requires PHP 7. Last I heard, our provider is still using PHP5. So, In order to get future updates, we'll have to switch from PHP 5 to 7. We should also be aware not to update October anymore in case for some reason there aren't any safety measures put in place for those of still running PHP 5.

**Comment by akien-mga** [comment]
Thanks for the notice; I guess October knew itself that it should not update, as when I did the auto-upgrade 423 was already out and still we got only 419. https://github.com/octobercms/october/releases

**Comment by akien-mga** [comment]
For the reference, details on the currently php version we have TuxFamily: http://hack.tuxfamily.org/phpinfo.php

**Comment by pcvonz** [comment]
[Here is more info](https://octobercms.com/support/article/rn-9) regarding the update. We'll be fine, but we should make any effort we can to update.

**Comment by akien-mga** [comment]
As discussed with the TuxFamily devs, we'll have the required PHP7 version when they upgrade the current Debian 8 infra to Debian 9, which was released a couple months ago. There is no ETA on the upgrade, but as long as there are no big security vulnerabilities announced in our current October version, we should be fine.

**Comment by mhilbrunner** [comment]
[PHP 5.6 security support will end December 31, 2018.](http://php.net/supported-versions.php)

**Comment by Calinou** [comment]
I believe this is now solved, as we've upgraded the PHP version to 7.2 to run the latest October version (this was required to fix the Patreon plugin).
