### ISSUE TITLE
Website Really Needs A Showcase Section

### ISSUE THREAD

**Issue by yusufkaanocak** [godotengine/godot-website#128]
I think godotengine.org really needs a showcase section. A week ago Game Maker was the first engine my best friend tried. I tried to convince him to use Godot but he saw all that games in showcase section of Game Maker and wanted to try that one. I know that there are no that huge titles made with Godot yet but there are great game jam games to show its power. Like securas' SealedBite.

I made a list of great games I found that is made with Godot because I guess you don't have time to search for them (like 54 games, I can send it if you want to see it) even if you just make a page for them I think it would be awesome. Beginners would be more interested on Godot and the community can go way bigger. Because newbie users doesn't know they can do anything they want with Godot and they want to see what they can do. They need examples.

This is just a suggestion. But I hope you will take it serious. Have a nice day Godot Devs. And congrats for becoming the most starred game engine.

**Comment by Calinou** [comment]
The showcase section we previously had was [removed](https://github.com/godotengine/godot-website/pull/117) because we don't have the manpower to maintain it. I don't think readding it would be a good idea at this point.

**Comment by yusufkaanocak** [comment]
But the Game Maker's showcase didn't changed for a long time too. 54 games can show what we need and if a new good game releases we can make a pull request to let you know or to add it.

**Comment by yusufkaanocak** [comment]
They made a  [video](https://www.youtube.com/watch?v=UEDEIksGEjQ) like this. That's kinda enough for me but Godot really need to have a showcase section on its website. I am closing this issue but I hope you will consider this.

**Comment by Calinou** [comment]
> They made a [video](https://www.youtube.com/watch?v=UEDEIksGEjQ) like this.

That was me :upside_down_face:
