### ISSUE TITLE
Left side of the downloads page should be vertically aligned to top

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#141]
**Operating system, Browser, Browser Version:**
Windows 10, Chrome 83.0.4103.61

**Issue description:**
Left side of the [downloads page](https://godotengine.org/download/windows) contains a logo and release version information, which is vertically adjusted to be centered. However, the right side with the link and other information can vary depending on the operating system you are downloading the engine for. For that reason the whole block can have varying height and the left side can be displayed at various levels.

I believe it would be better to adjust the left side to the top, always, making it clearly visible regardless of the right-side content.

This line seems to be the offender and can be adjusted to `start`, for example.
```css
.version-overview {
    ...
    justify-content: center;
}
```

**Screenshots (greatly appreciated if it’s a style issue)**

How it currently is:
[Linux](https://user-images.githubusercontent.com/11782833/84289350-0bf93600-ab4b-11ea-9cf5-a227c9c794a3.png)
[macOS](https://user-images.githubusercontent.com/11782833/84289381-161b3480-ab4b-11ea-892e-1429af5a789f.png)
[Windows](https://user-images.githubusercontent.com/11782833/84289428-229f8d00-ab4b-11ea-9085-dc394b50effe.png)

This would be better:
![image](https://user-images.githubusercontent.com/11782833/84289034-ae64e980-ab4a-11ea-9bda-20cc4f0b143f.png)

**Comment by Calinou** [comment]
This looks much better, but we should still add a small margin above the logo (~30-50 pixels).
