### ISSUE TITLE
Buttons on downloads page have unreadable color on hover

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#142]
**Operating system, Browser, Browser Version:**
Windows 10, Chrome 83.0.4103.61

**Issue description:**
When hovering over "Available on itch.io" and "Available on Steam" buttons the main text is too dark to be legible. It seems that the color is supposed to be pink, but is unset with another rule:

![image](https://user-images.githubusercontent.com/11782833/84290308-2e3f8380-ab4c-11ea-8cac-856ef8cf86a4.png)

**Screenshots (greatly appreciated if it’s a style issue)**

![image](https://user-images.githubusercontent.com/11782833/84290154-03552f80-ab4c-11ea-91d5-c2145adb735b.png)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-website/issues/75.

**Comment by YuriSizov** [comment]
Oops, sorry for not doing due diligence!
