### ISSUE TITLE
replace google font with local hosted free alternative

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-website#155]
**Operating system, Browser, Browser Version:**
All

**Issue description:**
Remove google front from godotengine.org and replace it with a local hosted free alternative.
This way visitors don't make a call to google servers and expose their metadata.
The front used is montserrat. Suggestions for an free alternative are welcome.

The files that would need a change are: 
godot-website/themes/godotengine/partials/head.htm (remove link to google)
godot-website/themes/godotengine/assets/css/main.css (add to new font)
godot-website/themes/godotengine/assets/ (place new font here)

I would like to work on this issue.

**Comment by Calinou** [comment]
@redoxCode Feel free to to open a pull request for this :slightly_smiling_face: 

Note that the website only supports modern browsers, so you should only include the `.woff` and `.woff2` formats.

PS: Don't forget to [add `font-display: swap;`](https://developers.google.com/web/updates/2016/02/font-display) to the `@font-face` declaration to improve perceived performance.

**Comment by Calinou** [comment]
This was resolved by https://github.com/godotengine/godot-website/pull/156, closing.
