### ISSUE TITLE
Q&A directs to scam 

### ISSUE THREAD

**Issue by ShalokShalom** [godotengine/godot-website#170]
See the link to the authors webpage of the Donut theme, that we are using on our questions and answers page.

It directs to http://www.amiyasahu.com/

**Comment by Calinou** [comment]
It looks like we have to modify the theme files to remove the link to the author's website.

cc @akien-mga

**Comment by akien-mga** [comment]
Fixed on the live instance (for the reference, in `qa-theme/Donut-theme/qa-donut-layer.php`).

There are some more references in the source code but they don't see used publicly.
