### ISSUE TITLE
Downloads broken

### ISSUE THREAD

**Issue by ehutch79** [godotengine/godot-website#172]
The downloads.tuxfamily.org mirror at least has certificate errors and to download export templates i had to manually trace  bunch of redirects which all had certificate errors. Same with direct downloads of godot itself.

**Comment by Calinou** [comment]
The certificate is still valid according to Firefox: 

![image](https://user-images.githubusercontent.com/180032/91301931-f8528880-e7a5-11ea-8b62-0c595891da9a.png)

**Comment by ehutch79** [comment]
Clearly this isn't on godot. so closing comment,
