### ISSUE TITLE
Some resources needed for new website.

### ISSUE THREAD

**Issue by djrm** [godotengine/godot-website#18]
I need some resources to complete the new website.

so the new design is this
![screenshot from 2018-01-21 14-17-28](https://user-images.githubusercontent.com/1103897/35198533-df925284-feb5-11e7-8785-291154d6ba9a.png)

what is needed:

* text for the main message (the current text is not friendly)
![screenshot from 2018-01-21 14-18-31](https://user-images.githubusercontent.com/1103897/35198543-0aed96b4-feb6-11e7-82fd-9cfa053a335e.png)

* text for this new section
![screenshot from 2018-01-18 11-47-06](https://user-images.githubusercontent.com/1103897/35198562-3f2cb680-feb6-11e7-84a1-d4bf57729187.png)

* cool screenshots of godot 3.0 projects (demos or whatever).

* new list of outstanding features (for the features page) with new text (current text are convoluted).

* list of 3 or 4 very outstanding features for the main page (like the ones from blender home page).

* os, and hardware requirements for platforms (also reasonable suggestions here are welcome)
![screenshot from 2018-01-21 14-21-53](https://user-images.githubusercontent.com/1103897/35198578-8231918a-feb6-11e7-9422-e913fdf27482.png)

* text for this
![screenshot from 2018-01-21 14-23-09](https://user-images.githubusercontent.com/1103897/35198593-a590f30a-feb6-11e7-95b0-e7c51e568d95.png)

* if someone is willing to make new screenshots for the community section, that would be welcome (but it is not top priority)

**Comment by Ghuus** [comment]
To kick start this discussion, I think for the main message we could use the Patreon description:

THE GAME ENGINE YOU WAITED FOR.

Godot is the first Completely Free and Open Source game engine in the same league as the current big, commercial ones.

[SPACE]

It offers a complete editor, dedicated 2D and 3D engines, animation tools, multi-platform export, plugins, a free asset store, and so much more!

[DOWNLOAD BUTTON]

**Comment by djrm** [comment]
the most urgent tasks that are actually blockers, are the features sections, and the fancy screenshots, so help in this area is greatly appreciated, the main text is not high priority and i would avoid too much discussion on those since it is a waste of time, and we have to finish this in a couple of days?

**Comment by Ghuus** [comment]
I agree with you!

About the features to highlight in the main page, would be nice to include the ability to extend the editor with the Tool Mode. Use GDscript to code your game and extend the editor. 

About the fancy screenshoots, we got some devs that are creating some cool looking projects with Godot:

https://twitter.com/guaranapps
https://twitter.com/kubecz3k
https://twitter.com/fracteed
https://twitter.com/yafd

We could ask them if they can contribute with some images for the new website.

**Comment by djrm** [comment]
yes, i already have the @kubecz3k screenshots, also, @akien-mga said he has some material from various projects (but still unclassified), if someone can provide the screenshots to me that would be better.

**Comment by djrm** [comment]
some text updates ive done (do not take into account the parts that do not make sense).

![screenshot from 2018-01-26 14-29-25](https://user-images.githubusercontent.com/1103897/35459387-9343ea8e-02a5-11e8-980d-12e254482b76.png)
![screenshot from 2018-01-26 14-29-56](https://user-images.githubusercontent.com/1103897/35459400-9c7ed604-02a5-11e8-8ba3-ffc12a820ded.png)
![screenshot from 2018-01-26 14-30-05](https://user-images.githubusercontent.com/1103897/35459402-9f9b4c0a-02a5-11e8-8047-a3dfa94e75d5.png)
![screenshot from 2018-01-26 14-30-10](https://user-images.githubusercontent.com/1103897/35459405-a29d0f74-02a5-11e8-96f1-9b6195539af1.png)

**Comment by djrm** [comment]
a lot of text was already discussed, so any further improvement suggestion will require a new issue.
