### ISSUE TITLE
Add a plugin to tag news articles

### ISSUE THREAD

**Issue by ShalokShalom** [godotengine/godot-website#182]
Currently, I can not add #Godot4 and #GDScript to a blog post like [this one](https://godotengine.org/article/gdscript-progress-report-new-gdscript-now-merged). 

That means I can not link all blog articles, regarded to the development of Godot 4 or that one of GDScript.

Which is both unfortunate. :disappointed: 

This solution does plug-in to our current blog solution and it is ready to use (and actually maintained)

TADA: https://github.com/scottbedard/blogtags 🥳

**Comment by Calinou** [comment]
Note that if we do this, we'll have to go over all previous articles to add tags when relevant.

**Comment by ShalokShalom** [comment]
Yes, I volunteer

**Comment by YuriSizov** [comment]
I'm afraid, this can only be done via the admin panel, and as such cannot be outsourced to contributors. I guess you can compile a list of links and tags, but Akien or Calinou would have to manually edit the records still.

**Comment by ShalokShalom** [comment]
Oh, ok. Maybe it is possible to configure the system in a way, that allows very narrow accessibility? Anyway, I will compile that list. We still have to come up with a list of tags. #Graphic, #Sound, #Godot3, Godot4, and so on?
What else?

**Comment by YuriSizov** [comment]
General things like #Release, #Release-Candidate can be useful.

**Comment by ShalokShalom** [comment]
Listed by articles or tags? So do you want them ordered like that:

```
Article 1:
Tag 1, Tag 2, Tag 4.
     
Article 2:
Tag 2, Tag 4.
```

Or more like this:

```
Tag1:
Article 3, Article 16.

Tag2:
Article 4, Article 6, Article 7.
```

So sorted by Articles or sorted by Tags?

**Comment by YuriSizov** [comment]
Articles can have multiple tags, can't they? So ideally it should be a list of articles and all of the tags that each one of them needs.

**Comment by ShalokShalom** [comment]
Yes, they can have multiple ones. You understood the question differently than I intended it, maybe?

How will you have the list presented? I guess it is beneficial in one way or the other, depending on how the admin console looks like. How is it easier to implement?

By listing all the articles, and which tag they have, or the other way around? How is the workflow?

😃

**Comment by YuriSizov** [comment]
> By listing all the articles, and which tag they have

This is what I've said. A list of links and the corresponding tags.

**Comment by YuriSizov** [comment]
The new static website generator supports multiple categories/tags, though we don't utilize that functionality yet. Anyway, no plugin needed, we can just start to slowly use multiple categories.
