### ISSUE TITLE
News preview image is low resolution

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#19]
**Operating system, Browser, Browser Version:**
Windows 7, Firefox Nightly (60a1) from today

**Issue description:**
The preview image for the news articles seems to be upscaled from low resolution thumbnails:
![image](https://user-images.githubusercontent.com/4701338/35503216-cb238e5a-04df-11e8-9f96-035bc9d1dcac.png)

While the blog posts have it in higher res:
![image](https://user-images.githubusercontent.com/4701338/35503250-dc9807d8-04df-11e8-9959-4bac29bdc7f0.png)
(maybe too high btw, we should likely set a max height?)

I suspect that we might be using the thumbnail generated for the October backend instead of the actual full-res image:
![image](https://user-images.githubusercontent.com/4701338/35503305-0b2b6da6-04e0-11e8-9ec8-bd14d41a2995.png)

**Comment by HumayunE** [comment]
Image is used as a background image, I have tried some modifications Look:
![screen shot 2018-01-29 at 2 46 34 pm](https://user-images.githubusercontent.com/10536341/35503914-5300b32a-0503-11e8-8486-87dafb94242d.png)

**Comment by akien-mga** [comment]
Yeah but that's still the wrong image being used. It should be https://godotengine.org/storage/app/uploads/public/5a6/856/519/5a685651987ce263514865.png

**Comment by HumayunE** [comment]
I just noticed, in blog post it is the same image but stretched.

**Comment by akien-mga** [comment]
Here's how we include the proper image in the OGP metadata: `{{ post.featured_images[0].path }}`

Current code is https://github.com/godotengine/website/blob/189f6032f2bc14c8f2910ebb2aadc8106c7fb12d/themes/godotengine/layouts/news.htm#L59

**Comment by akien-mga** [comment]
Actually fixed in master already (189f6032f), the live instance was just outdated (it was using `100` instead of `400` previously for thumbnailing).
