### ISSUE TITLE
Loading home page gives a 404 error, but loads anyways

### ISSUE THREAD

**Issue by name-here** [godotengine/godot-website#194]
**Operating system, Browser, Browser Version:**
Firefox 81.0.1
Brave 1.14.84 Chromium: 85.0.4183.121 (64-bit)

**Issue description:**

Loading [godotengine.org](https://godotengine.org) gives a 404 error, but loads the page with no visible issues.  Brave shows a message saying the page is missing, while Firefox only shows it in the network inspector.  This seemed to happen with every page on godotengine.org I loaded, but I only tested a few.

**Screenshots (greatly appreciated if it’s a style issue)**
<img width="1440" alt="Screen Shot 2020-10-21 at 3 39 01 PM" src="https://user-images.githubusercontent.com/26884090/96774232-b021a200-13b3-11eb-8710-9dcfa3f5c46f.png">

**Comment by YuriSizov** [comment]
Can confirm. Related to 1.0.469 update and https://github.com/godotengine/godot-website/commit/6ccaa74d0a76dc01416b7e0edd5dfe94237fd29b maybe?

**Comment by Calinou** [comment]
I really have no idea what caused the website to fail loading when a custom 404 page was added. But now, it seems every page is considered a 404 page? I don't even…

**Comment by Calinou** [comment]
Closing in favor of #197.
