### ISSUE TITLE
Website is missing from relevant search engine queries due to returning 404 status code on most pages

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#197]
**Operating system, Browser, Browser Version:**
Tested on Google and DuckDuckGo

**Issue description:**
As reported on Discord and verified by me, if you search for "godot engine" on a search engine, you won't get the official website as one of the results. At least, not one of the immediate results.

The official docs, the GitHub repository for the engine, Steam and itch.io distributions, and the Wikipedia article are featured prominently, while the official website can only be found in passing with links to random articles or even the beta online editor. The landing page, the features page and most importantly the downloads page are nowhere to be found.

Godot is a recognized term both on Google and on DDG, there is a card shown for each of the searches, yet even that is lacking a link (that said, maybe links are not shown there regardless).

What is expected for this "godot engine" query is [this](https://user-images.githubusercontent.com/11782833/97804791-21d6d700-1c63-11eb-9b08-5be68c2a35ba.png) (You'll have to use your imagination to replace the name of the entity present on the image with "Godot"). And [the same for Google](https://user-images.githubusercontent.com/11782833/97804807-4468f000-1c63-11eb-882f-4b231f88835f.png).

I've personally not done a lot of work related to the SEO. Are those results based on the sitemap?

**Screenshots (greatly appreciated if it’s a style issue)**

Here are examples taken in the Incognito mode of Google Chrome, thought the same applies for the normal mode even if some links are a bit more personalized:
[Google results](https://user-images.githubusercontent.com/11782833/97804630-47171580-1c62-11eb-944c-c906b8e5b59e.png)
[DDG results](https://user-images.githubusercontent.com/11782833/97804670-73329680-1c62-11eb-8e62-48543291dcdb.png)

**Comment by Calinou** [comment]
This is because all pages except blog articles return a 404 status code. This has been occurring in production since the CMS and plugins were upgraded two weeks ago.

The issue is likely in the blog plugin. This doesn't occur when I disable the Blog plugin and remove references to its components in the homepage.

One of my suspects was https://github.com/rainlab/blog-plugin/commit/df66b382cd11b791b638df56180e4f3aa6832986, but I tried to modify the 404 error code to return 403 instead and the resulting resonse code didn't change when loading the homepage.

**Comment by YuriSizov** [comment]
Back to normal on Google for me (but not on DDG yet).
![image](https://user-images.githubusercontent.com/11782833/97893800-ce3bba80-1d42-11eb-9f58-e07b56dba7be.png)

So I think we can unpin the issue 🙂
