### ISSUE TITLE
Download page does not detect OS, defaults to Linux

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#20]
**Operating system, Browser, Browser Version:**
Windows 7, Firefox Nightly (60a1) from today

**Issue description:**
When going to https://godotengine.org/download it defaults to the Linux downloads even while I'm on Windows.

It should autodetect the platform, otherwise too many users will end up downloading the Linux build and wonder why it doesn't run.

Also, it would be nice to put the platform logos in monochrome in their tabs, to make it clearer.

Additionally, I think we should leave out the op.godotengine.org:81 mirror for 3.0-stable. It's only offered over HTTP and Windows 10 is even more paranoid with unsigned binaries downloaded over HTTP instead of HTTPS.

**Comment by djrm** [comment]
i will need another plugin to detect the user agent string ("well at least easily") server side. and about the mirrors, so should i remove them?

**Comment by akien-mga** [comment]
Yeah remove the op.godotengine.org mirror. But you can keep the CSS you wrote for it, as we'll likely be adding good HTTPS mirrors in the future.

**Comment by djrm** [comment]
ok, fixed by e2fbb6c84723ef5f172928b01716455385c75e0e
