### ISSUE TITLE
License tutorial page 404s

### ISSUE THREAD

**Issue by LaffertyDev** [godotengine/godot-website#205]
**Operating system, Browser, Browser Version:**
Kubuntu 20.04, Firefox, 83.0

**Issue description:**
Click on "Complying with Licenses". Expect to be taken to [good link](https://docs.godotengine.org/en/stable/tutorials/legal/complying_with_licenses.html) but taken to [bad link](https://docs.godotengine.org/en/latest/tutorials/legal/complying_with_licenses.html)

**Screenshots (greatly appreciated if it’s a style issue)**
n/a

Page: https://godotengine.org/license

**Comment by deralmas** [comment]
Since its respective PR has been merged, shouldn't this issue be closed?

**Comment by Calinou** [comment]
> Since its respective PR has been merged, shouldn't this issue be closed?

Indeed, thanks for the reminder :slightly_smiling_face:
