### ISSUE TITLE
Add the showcase to the tabs on top of the website.

### ISSUE THREAD

**Issue by Maciej-Gorczyca** [godotengine/godot-website#212]
**Operating system, Browser, Browser Version:**
WIndows 10 Chrome

**Issue description:**

Currently showcase is hard to find and arguable the easiest way to show users what is possible with the engine. Make navigating to it easier by adding link at a top of the page

**Screenshots (greatly appreciated if it’s a style issue)**
![Capture](https://user-images.githubusercontent.com/30668026/102282467-8eaee380-3f28-11eb-8c92-13fc7d225e2f.PNG)

**Comment by YuriSizov** [comment]
We are running out of space up there. It needs to be rethought completely at this point, because one more item or even just i18n changes make this split between two groups of items indistinguishable.

**Comment by name-here** [comment]
If #290 gets implemented, the Features link could be removed, probably making enough room to add a Showcase link.

**Comment by YuriSizov** [comment]
No, it doesn't make sense to remove a link like that, even if your proposal is implemented. It's important to leave clear navigation, for visitors and bots alike.
