### ISSUE TITLE
Allow linking to headers on news pages and the Features page

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#214]
On news pages and static pages like [Features](https://godotengine.org/features), we should add anchor link icons that appear when a heading is hovered. When the anchor icon is clicked, it navigates to an anchor link that can then be shared to others for easier referencing. For example: https://godotengine.org/features#xrsupport

**Comment by ampsteric** [comment]
hey! , I would be happy to help.
Please assign me this issue under hacktoberfest.

**Comment by nsundriyal62** [comment]
please assign this issue to me !

**Comment by Ymanawat** [comment]
@Calinou I tried to do that and created a pull request, please review it.

**Comment by JohnVeness** [comment]
I think this can be closed as completed...
