### ISSUE TITLE
The logo shows up twice on the header (affects all pages) [press Ctrl + F5 to clear cache]

### ISSUE THREAD

**Issue by kyleguarco** [godotengine/godot-website#229]
**Operating system, Browser, Browser Version:**
Debian Linux (Sid), Firefox 84

**Issue description:**
On all pages of the site, the logo appears twice. One instance is a dark theme variant, the other is a light theme variant.

I think it happens here (introduced in #218?)
https://github.com/godotengine/godot-website/blob/6edb7650e44d5dd631dc59afe408d38e473ddac8/themes/godotengine/partials/header.htm#L14-L17

**Screenshots (greatly appreciated if it’s a style issue)**
![out](https://user-images.githubusercontent.com/23580612/103575502-d37ec800-4e9f-11eb-890d-7cf006bb007c.png)
![out2](https://user-images.githubusercontent.com/23580612/103575505-d5488b80-4e9f-11eb-898d-7896a6ca269a.png)

**Comment by kyleguarco** [comment]
To clarify, I don't think this is happens to everyone. I can't set the dark theme on my laptop browser currently ([using a custom browser theme](https://github.com/EliverLara/firefox-sweet-theme), but the bug still occurs even with the default one), but my phone picks up on the dark theme just fine and uses the appropriate logo.

Taken on a **Moto G8 Power, Android 10, Firefox 84.1.2**
![Screenshot_20210104-152144~2](https://user-images.githubusercontent.com/23580612/103576489-3ae94780-4ea1-11eb-95ee-3700ddc08cf1.png)

**Comment by YuriSizov** [comment]
You need to flush your browser cache. The issue happens because your browser gives you an outdated CSS file, but the layout served by the server is new. Press Ctrl-F5, it should help.

**Comment by Calinou** [comment]
This is a caching issue which can't be solved until we add proper cache headers and cache busting on October's side.

As @pycbouh said, press <kbd>Ctrl + F5</kbd> while on the website to clear the page cache.

I'll leave this pinned for a few days so that people can notice this issue more easily.

**Comment by kyleguarco** [comment]
Ah, clearing the cache does fix the issue. Sorry!
