### ISSUE TITLE
Use PNG for the OpenGraph og:image meta tag

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#231]
**Operating system, Browser, Browser Version:**
🙃 

**Issue description:**
I was wondering why embeds for the website links on Discord do not include an image:
![image](https://user-images.githubusercontent.com/11782833/103646351-96333c80-4f6a-11eb-90dd-9e7215ccc135.png)

We are using an SVG file for the `og:image` meta tag (`https://godotengine.org/themes/godotengine/assets/logo.svg`), but from my quick research this does not seem to be supported by the standard. https://ogp.me/ does not specify what is supported, I don't think, but multiple sources on Google suggest that SVG is definitely out.

As such, I suggest we replace it with a PNG. OpenGraph supports multiple values for tags, with the topmost valid value being used by the parser, so I think we can just add a second tag underneath with a PNG link, and it should fix things.

There is also something generally off about that embed pictured above. I don't understand why it shows that description and title. Meta tags for https://godotengine.org/contact are

```html
<meta property="og:title" name="twitter:title" content="Free and open source 2D and 3D game engine">
<meta property="og:description" name="twitter:description" content="Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.">
```

Yet, when embedded, it shows as `Contact` and `Contact page`. Maybe it is cached somewhere, but I get the same result on Telegram as well, so that makes it less likely:

![image](https://user-images.githubusercontent.com/11782833/103647522-83216c00-4f6c-11eb-9121-644bb7586129.png)

**Screenshots (greatly appreciated if it’s a style issue)**

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face: 

> There is also something generally off about that embed pictured above. I don't understand why it shows that description and title.

There's a `description` front matter property in `contact.htm` if you look at the top. Maybe we should amend it.
