### ISSUE TITLE
Add a tutorial place with discord channel bot

### ISSUE THREAD

**Issue by marcosn41** [godotengine/godot-website#235]
Hey!

I think it would be nice to have a more robust tutorial area with thumbnails that draw more attention not only in videos but also in text.

One suggestion is to have a bot that posts the tutorials that are placed on the #tutorials discord channel in this area. It has a lot of good things but it sucks to look for something there.

**Comment by Calinou** [comment]
This issue tracker is only about the website, not the Discord platform. Please make suggestions on the Discord server's `#discord-suggestions` channel instead.

With this said, I think integrating a Discord bot that interacts with the website sounds very difficult and probably isn't worth the effort.
