### ISSUE TITLE
Add godot con to upcoming 2021 events

### ISSUE THREAD

**Issue by omicron321** [godotengine/godot-website#259]
**Operating system, Browser, Browser Version:**
any
**Issue description:**
Undocumented next godot con in next days at https://godotengine.org/events
Last article archive: https://godotengine.org/article/call-for-participation-online-godotcon-2021

Bonus : a (corner) banner in home page for that event

Past event as example : https://godotengine.org/events/past

Past 2020 con schedule announcement: https://godotengine.org/article/schedule-godotcon-2020-brussels

**Comment by Calinou** [comment]
@Omicron666 I can handle the rest, but do you have a draft for an article? I have quite a lot of stuff going on these days, so I can't do everything at the same time.

**Comment by omicron321** [comment]
> 
> 
> @Omicron666 I can handle the rest, but do you have a draft for an article? I have quite a lot of stuff going on these days, so I can't do everything at the same time.

Better ask to godotcon at godotengine · org they must have all required materials, maybe even some article draft, idk.

As author of last related article, @StraToN could we have your input ?

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot-website/pull/263, closing.
