### ISSUE TITLE
Downloading PDF from the GodotCon news yield unexpected results

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#269]
**Operating system, Browser, Browser Version:**
Windows 10, Chrome 87.0.4280.141
Also confirmed in Firefox Nightly by akien.

**Issue description:**
Pressing the *Download this PDF* link at the bottom of the [GodotCon 2021 schedule news](https://godotengine.org/article/online-godotcon-2021-schedule) doesn't correctly download a PDF document. Instead, it is loaded and immediately replaced in the browser history by the page you are currently on.

![image](https://user-images.githubusercontent.com/11782833/105475384-5c736d00-5cb0-11eb-86e7-9403036d9979.png)

I think this may be an issue with the plugin we use for faster page loading (#222). Maybe also the same issue as #228.

**Screenshots (greatly appreciated if it’s a style issue)**

**Comment by YuriSizov** [comment]
Maybe we can add some file extentions to the [`prevent` setting](https://barba.js.org/docs/advanced/strategies/#prevent)? @Calinou 

Barba does successfully prefetch a link though:
![image](https://user-images.githubusercontent.com/11782833/105483256-a06b6f80-5cba-11eb-900b-aed3bfe960e6.png)

**Comment by Calinou** [comment]
> Maybe we can add some file extentions to the prevent setting? @Calinou

Indeed, this is how it should be fixed. If only Barba.js did it by default…
Feel free to open a pull request for this.

In the meantime, I edited the post to add the `data-barba-prevent` attribute to the link. Clicking the PDF link should work as expected now.
