### ISSUE TITLE
Q&A and Asset Library links on the rocket.chat announcement don't seem to work

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot-website#284]
**Operating system, Browser, Browser Version:**
Windows 10; Firefox 85.0 (64-bit)

**Issue description:**
On the announcement for the [rocket.chat chatroom that was recently created](https://godotengine.org/article/new-communication-platform-godot-contributors), none of the links to the "Q&A" or "Asset Library" sections seem to work. When normally clicking on them (not using "Open in new tab" or the like), the screen will dim (or gray? not sure which is a better descriptor here) as normal, and then will redirect back to the blog posts after a couple seconds.

I'm not sure what's going on here to cause this with those links alone. Looking in the developer tools reveals that the script is, in fact, trying to load the asset library page -- but something in the script might be telling it to abort and reload the blog post when it sees that it's not the same page structure.

This does not seem to happen for any other links on that announcement post.

**Screenshots (greatly appreciated if it’s a style issue)**
None, this should be easy to replicate on your own (but I will provide video of the issue if requested)

**Comment by YuriSizov** [comment]
See also #269. This is an issue with the library we use to load pages faster. Requires some tuning, it seems.

Should work if you open those links in a new tab.

**Comment by Calinou** [comment]
Fixed in the article by adding `data-barba-prevent` attribute on the problematic links.

As for the rest of the issue, it's a duplicate of https://github.com/godotengine/godot-website/issues/269.
