### ISSUE TITLE
no-reply@godotengine.org sent a sketchy link

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot-website#291]
**Operating system, Browser, Browser Version:**
Windows 10,  Android 10

**Issue description:**
Email sent from no-reply@godotengine.org contained a link to a Q&A answer, but the link was broken into 3 lines. and actually lead to a different website.
Luckily, VirusTotal says no viruses detected there, but there could have been.
I didn't notice until I clicked it and it started redirecting to different sites.

Link should not have been broken.

**Screenshots (greatly appreciated if it’s a style issue)**
![SketchyLink](https://user-images.githubusercontent.com/60025044/108234216-33f15e00-710a-11eb-9d1c-dacf0af46187.png)

**Comment by Calinou** [comment]
This is because the link is particularly long, and GMail's preview is forcing all text to wrap. I don't think we can do anything about this.

**Comment by pycbouh** [comment]
> and actually lead to a different website.

What website was that? If the link is visually broken into separate lines, it should still be one tag and one URL, the visuals don't matter in that regard.

**Comment by Error7Studios** [comment]
It's weird, because I've seen links that were like 15 wrapped lines long in Gmail, but never seen a link actually break into different links like that.
(Longest I can find right now is only 2 lines, but I've definitely seen longer)
![AmazonLink](https://user-images.githubusercontent.com/60025044/108237789-dced8800-710d-11eb-8e8f-82d94281c2e0.png)

> What website was that?

The second and third line was a wrapped link.
Here are the actual links (I clicked the second one)
1. https://godoteng
2. ine.org/qa/95461/code-replace-text-file-between-points-doesnt-work-correctl
y?show=95496#a95496

**Comment by pycbouh** [comment]
Just to double check: you're saying the second line was its own link, like that `ine.org/qa/95461/code-replace-text-file-between-points-doesnt-work-correctl`?

**Comment by Error7Studios** [comment]
It was this clickable link
`ine.org/qa/95461/code-replace-text-file-between-points-doesnt-work-correctly?show=95496#a95496`
Just wrapped over two lines:
```
ine.org/qa/95461/code-replace-text-file-between-points-doesnt-work-correctl
y?show=95496#a95496
```

**Comment by pycbouh** [comment]
That's weird.
@Calinou thoughts? Do we have any control over the way emails are composed?

**Comment by Calinou** [comment]
> Do we have any control over the way emails are composed?

They're composed by Question2Answer, and from looking at its administration interface, I can't find any way to configure how emails are sent (or even fall back to plain text).

**Comment by Calinou** [comment]
I've gotten an email where the link was wrapped. This seems to happen because the body text has very long lines and Question2Answer forcibly wraps all the text in the email when this happens.

But yes, this is core behavior which we can't control ourselves.

**Comment by Calinou** [comment]
Closing, as this is something that can't be fixed on our end.
