### ISSUE TITLE
Incorrect proportions

### ISSUE THREAD

**Issue by fire** [godotengine/godot-website#306]
**Operating system, Browser, Browser Version:**
win10, firefox, and 86.0.1

**Issue description:**
Incorrect proportions on the theme near "showcase".

**Screenshots (greatly appreciated if it’s a style issue)**
![image](https://user-images.githubusercontent.com/32321/111884662-516f4d00-8980-11eb-9061-b6dcac111055.png)

**Comment by YuriSizov** [comment]
You need to flush your browser's cache. This is due to layout changing recently, but your browser using an outdated CSS file.

<kbd>Ctrl-F5</kbd> should do the trick.

**Comment by Calinou** [comment]
I'll try to add some manual cache busting solution to solve this. I'll pin this issue in the meantime so it can be seen easily.
