### ISSUE TITLE
Asset library page is broken in Vivaldi

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-website#31]
**Operating system, Browser, Browser Version:**
Linux Mint 18.3, Vivaldi 1.13.1008.44 x64

**Issue description:**
This page looks broken in Vivaldi - https://godotengine.org/asset-library/asset

**Screenshots (greatly appreciated if it’s a style issue)**

![image](https://user-images.githubusercontent.com/3036176/35575665-0effdca0-05ee-11e8-8905-e9aae060e576.png)

**Comment by leonkrause** [comment]
Were you previously logged into the asset library per Github login?

**Comment by Chaosus** [comment]
Yeah, I clear the cache, and problem is gone..
