### ISSUE TITLE
Metatags use old godot name

### ISSUE THREAD

**Issue by danbulant** [godotengine/godot-website#315]
![image](https://user-images.githubusercontent.com/30036876/113315515-a6f71280-930d-11eb-815b-f17a93e0d90a.png)

The description and the icon is from the old godot style, not the new Godette (just noticed this when I sent the link to friends to share the name change).

<details>
  <summary>01. Apr 2021</summary>
  
  I know it's just temporary, but at least for the home page would serve as a good to have detail.
  
</details>

**Comment by Calinou** [comment]
April Fools will only run for a few more hours, so I won't bother doing this (as this could potentially negatively impact SEO for next week).
