### ISSUE TITLE
GodotCon banner shrinks page horizontally on mobile

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot-website#319]
**Operating system, Browser, Browser Version:**
Android 10, Chrome 89
**Issue description:**

See screenshot
**Screenshots (greatly appreciated if it’s a style issue)**
![Screenshot_20210409-142257](https://user-images.githubusercontent.com/50304111/114236634-23f23f80-993f-11eb-85d0-5e0118eb82e5.png)

**Comment by AaronRecord** [comment]
This problem is back again...

**Comment by YuriSizov** [comment]
It doesn't shrink for me on an actual device, but there is a horizontal scroll because of the corner sticking out. It does shrink in the Chrome emulator though.

**Comment by AaronRecord** [comment]
Yeah it is a little different this time, for me now it looks fine at first but there's a horizontal scroll bar and if I scroll over it's empty except the edge of the banner (whereas the first time there was no scrollbar)
