### ISSUE TITLE
Make export templates available on itch.io as well

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot-website#328]
(Don't know, if it's the right repo, but here goes...)

**Issue description:**

The tuxfamily servers are pretty slow to download from. Itch's servers on the other hand are blazingly fast. Could you please add the export templates downloads to itch as well?

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/18329.

In the meantime, use [this mirror](https://archive.hugo.pro/godot-tuxfamily/) hosted by yours truly.

**Comment by dploeger** [comment]
Thanks a lot!

**Comment by Calinou** [comment]
[A GitHub Releases mirror has been added](https://github.com/godotengine/godot-website/pull/360), making itch.io export template downloads not really relevant to propose anymore. Closing.

**Comment by dploeger** [comment]
Yayyy!
