### ISSUE TITLE
Specify on the Windows download page that Scoop requires the `extras` bucket to be added to install Godot

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#34]
On the [Windows Download page](https://godotengine.org/download/windows), it should be specified that the Scoop ["Extras"](https://github.com/lukesampson/scoop-extras) bucket must be added *before* entering `scoop install godot`. This is done by entering `scoop bucket add extras`; this is required because Godot is not in the main bucket since it is a graphical application (see [Criteria for including apps in the main bucket](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket)).

**Comment by djrm** [comment]
fixed by f84988ccbb7974960d3cbe6381453b5c9ec46131
