### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by troys-code** [godotengine/godot-website#348]
### Environment

Windows 10, Google Chrome, fast internet connection.

### Issue description

Steps to reproduce:

- visit https://godotengine.org/download/windows
- chose the "Mono version (C# support)"
- click download x86_64
- download takes a few minutes, running at about 50KB/s

My internet connection is many MB/s (I can provide a speedtest on request).

**Screenshots**

This issue has been known for a while: https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/troy/2021/06/Discord_MGgwCm7SaPBUqT6H.png

### See also

There is also https://github.com/godotengine/godot-website/issues/105 which suggest using torrents, but that requires a torrent app to download.

**Comment by troys-code** [comment]
Apparently I can use Steam to download Godot faster? I don't have steam installed though (I make games for mobile).

**Comment by YuriSizov** [comment]
TuxFamily servers are known to be unreliable in some parts of the world. You can indeed use Steam or itch, but not for the Mono version, or a mirror by @Calinou hosted at https://archive.hugo.pro/godot-tuxfamily/ which has everything.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-website/issues/105 (same cause).
