### ISSUE TITLE
GodotCon banner shrinks page horizontally on mobile

### ISSUE THREAD

**Issue by Al-Shahrior** [godotengine/godot-website#349]
**Operating system, Browser, Browser Version:**
Android 10
Firefox 89.1.1
![Screenshot_20210702-121004](https://user-images.githubusercontent.com/31450209/124229516-8f5b4000-db2f-11eb-8a10-b74909d5e6ac.png)

**Issue description:**
It's a style issue screenshots added. 

**Screenshots (greatly appreciated if it’s a style issue)**
![Screenshot_20210702-120955](https://user-images.githubusercontent.com/31450209/124229500-88ccc880-db2f-11eb-996c-874c90447dfe.png)

**Comment by Calinou** [comment]
This is a duplicate of https://github.com/godotengine/godot-website/issues/319 which seems to have manifested again. I have no idea how to fix this at this point…

The GodotCon banner will be removed on July 4th, which will fix this problem anyway.

**Comment by Calinou** [comment]
Closing, as the GodotCon banner was removed a while ago.
