### ISSUE TITLE
Add credits on hover for the artwork we use as showcase

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot-website#35]
Someone just asked what was game on the website on the Discord server, so I think it's a good idea to add a link to the game or its [YouTube video](https://www.youtube.com/watch?v=QWoQe9ZOwTU) at the bottom left or right of the image.

**Comment by DleanJeans** [comment]
Q&A: [Information or details on background image of GODOT main home page?](https://godotengine.org/qa/24070/information-details-background-image-godot-main-home-page)

**Comment by djrm** [comment]
i think the name changed, also not sure if the title is definitive by now (that games still a work in progress), i plan to put the title along with the image maybe @kubecz3k knows better.

**Comment by akien-mga** [comment]
Regardless of the credits for that specific image, we need a system to
properly credit *all images* we use (like on the Features page, or in blog
posts).

2018-02-26 2:30 GMT+01:00 Daniel Ramirez <notifications@github.com>:

**Comment by kubecz3k** [comment]
@DleanJeans thanks for thinking about our game! Regarding our game specifically I don't think it's super great idea to link to the YT video. I will work on game website/devblog later next month so that might be good place to refer :)
Also by the way the final name of the game is 'RivenTails Defense'

**Comment by djrm** [comment]
@akien-mga yeah, but such system should be visible on mobile and desktop, and i dont know if i should make the credits always visible and damage the design, or add some hover effect but it wont be visible on mobile. 

I also think this is important but i want to find something unintrusive and good looking

**Comment by akien-mga** [comment]
I wouldn't bother about mobile, hover only on desktop should be good enough
and good looking IMO.

>

**Comment by akien-mga** [comment]
Renamed the issue to encompass all artwork we use (at least the homepage/features page, but if possible it would be cool to have the caption system available from the blog plugin too).

**Comment by YuriSizov** [comment]
> if possible it would be cool to have the caption system available from the blog plugin too

As far as I can see if you click on the uploaded files, images included, they have a `title` and a `description` fields that can be edited. It's only a matter of using them in the template properly. Currently description is used for the `alt` attribute.

![image](https://user-images.githubusercontent.com/11782833/92030497-ca55e100-ed6f-11ea-8296-db5edcd5d5d8.png)
![image](https://user-images.githubusercontent.com/11782833/92030510-cf1a9500-ed6f-11ea-8489-6e6e769c3d0d.png)

**Comment by coppolaemilio** [comment]
I think we can close this one? Or am I missing something? 🤔

**Comment by YuriSizov** [comment]
We have credits for the main image on the home page, and we have a way to credit projects and people for the cover image in news, but the rest is not credited. The Features page comes first to mind, for example.

**Comment by YuriSizov** [comment]
The showcased projects all have credits on the page itself. For the features page we'll be remaking it and should address it as we change the design and the media content on it. If there are any other uncredited pieces of work on the website, please open new issues (individual, or grouped), so it can be properly addressed.
