### ISSUE TITLE
Tabs in news page has white padding when viewed in narrow window

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-website#353]
**Operating system, Browser, Browser Version:**
macOS 11.4 / Chrome 91.0.4472.164 & Safari 14.1.1

**Issue description:**

When the browser window is narrow, there are unexpected white padding below & right to the news page's tabs.

**Screenshots (greatly appreciated if it’s a style issue)**
![padding](https://user-images.githubusercontent.com/372476/126042660-0f63ffd9-5d07-4685-9554-4549cf53f880.png)

**Comment by YuriSizov** [comment]
That looks like the space for scrollbars. What's your window resolution?

**Comment by timothyqiu** [comment]
It's about 880x700 in the screenshot.

**Comment by Calinou** [comment]
We should probably disable `overflow-y` on that tab container.

**Comment by bits-by-brandon** [comment]
@Calinou confirmed that https://github.com/godotengine/godot-website/pull/364 fixed this. Should we close this issue?

**Comment by YuriSizov** [comment]
Yes, good call. It wasn't linked properly, but it seems to be fixed.
