### ISSUE TITLE
Not easy to choose Showcase and Web Editor pages on mobile devices

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot-website#357]
Operating system, Browser, Browser Version:
HarmonyOS 2.0.0 / Firefox 91.2.0

Issue description:

When touching on More, it jumps to the Contact Us page right away, leaving no choice for user to select Showcase and Web Editor pages.

https://user-images.githubusercontent.com/28705694/130254737-287c0d51-1e10-4a8e-8da2-f097bddc967b.mp4

**Comment by Calinou** [comment]
I added the Showcase page to the mobile menu in https://github.com/godotengine/godot-website/commit/d4e55ae3fe847430f26fe0d5eebf7512c280b2af, but it seems it's not present anymore for some reason.

**Comment by Calinou** [comment]
The dropdown is intentionally not present on mobile, but it seems the media query isn't being respected properly on your viewport width. This is an issue if your viewport width is between 900 and 1199 density-independent pixels (which will mainly happen on tablets or foldable phones).
