### ISSUE TITLE
Navbar more dropdown overlaping

### ISSUE THREAD

**Issue by naolarega** [godotengine/godot-website#361]
Windows 10 pro 20H2, chrome 93.0.4577.63

On the home page the more dropdown is hidden it bottom most options on a screen size of `1366x768`

![image](https://user-images.githubusercontent.com/45383986/132996431-4620734a-d11d-4312-ae00-efa3bbb78c77.png)

**Comment by YuriSizov** [comment]
Should be a straight-forward fix. The menu is z-index 1 and the body below is z-index 2.
