### ISSUE TITLE
Image hover effect on blog triggers blinking when cursor is on the edge

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#369]
**Operating system, Browser, Browser Version:**
Mageia 9 Linux, Firefox Nightly 94.0a1 from 2021-09-25.

**Issue description:**
We have a hover effect on images which highlights the fact that it's clickable, and on the blog, it leads to a weird bug as apparently there's a mismatch between hitboxes for normal and hover styles. I thought this was reported already but couldn't find the issue.

It's been like this for a while (since this hover effect was added).

The bug seems to happen only on the blog, but for any image (both banner picture and in-article images).

**Screenshots (greatly appreciated if it’s a style issue)**

https://user-images.githubusercontent.com/4701338/134922569-162f964a-9ac4-4387-8e2d-4e2ddfa1901d.mp4

**Comment by YuriSizov** [comment]
Note for future self (or anyone who wants to make a PR) — this may help

* Remove `max-width: 85%` from the cover image.
* Add the following to the anchor around that image instead:
```
    display: inline-block;
    max-width: 85%;
```

This seems to fix the size of the anchor area in Chrome (and also restore the hover effect in Chrome), so it may help with the FF issue in OP as well.

Tested in browser on https://godotengine.org/article/introducing-gd-extensions

**Comment by Calinou** [comment]
> display: inline-block;
>     max-width: 85%;

This indeed fixes the issue on the cover image in Firefox 95, but images within the article won't be centered anymore if they're not wide enough.

PS: I got the same effect if I just add `display: inline-block;` to the existing image declaration (without adding it to the anchor).

**Comment by akien-mga** [comment]
I think that if we can't find an easy solution to this issue, we should revert the change that introduced it. It really makes the blog look bad on Firefox.
