### ISSUE TITLE
A slight misalignment in footer

### ISSUE THREAD

**Issue by code-reaper08** [godotengine/godot-website#374]
**Operating system, Browser, Browser Version:**
Windows 10, Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Issue description:**
There's a slight misalignment in footer, on mobile devices.

**Actual**

![image](https://user-images.githubusercontent.com/64256342/137790182-c193d6f6-8872-4c42-91e6-a0d62bbe8a1a.png)
[We can see, a slight alignment to the left here]

**Expected**

![image](https://user-images.githubusercontent.com/64256342/137790395-9f5feed7-1480-4f4d-b7f0-235dccf91b77.png)
[Here, we can see it's centre aligned, and stays even with other contents.]

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-website/pull/375.
