### ISSUE TITLE
I'm developing a new website for godot (only front-end)

### ISSUE THREAD

**Issue by starfish-designer** [godotengine/godot-website#387]
Hello I'm developing a new website for godot for a fair price if you are interested tell me. Please see my portfolio on my website:
https://starfishdesigner7.000webhostapp.com/portfolio.html

I made a a little bit from first page look this picture:
![Godot Website](https://user-images.githubusercontent.com/89623278/155895210-15b99d43-2607-443d-b4de-10d374fbf057.png)

**Comment by Calinou** [comment]
Hello!

Thanks for the offer, but we are currently not interested in having a new website design.
