### ISSUE TITLE
Outdated "Animate Everything" image in "Features" page

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-website#39]
**Issue description:**
In the "Animate Everything" section, the image used is from an older version of Godot.

**Comment by djrm** [comment]
yeah, someone please contribute one

**Comment by ampsteric** [comment]
Please assign me this issue under hacktoberfest. , if it is still open.

**Comment by YuriSizov** [comment]
We're planning to rework the entire page soon, so this specific issue will be resolved alongside.
