### ISSUE TITLE
Add link to FAQ in Navbar Header and/or sidebar of Q&A

### ISSUE THREAD

**Issue by leogott** [godotengine/godot-website#390]
**Operating system, Browser, Browser Version:**
all
**Issue description:**
In the Q&A, there are many questions, which are asked frequently. Often the question askers are not aware of there being an FAQ in the docs, [(Example)](https://godotengine.org/qa/1705/how-does-gdscript-compare-to-python) as the Header doesn't contain a link to it. And neither does [the readme.](https://godotengine.org/qa/57/readme-how-to-use-this-q%26a)

The Navbar Header and/or the sidebar of the godotengine Q&A should contain a link to [the FAQ](https://docs.godotengine.org/en/stable/about/faq.html)
**Screenshots (greatly appreciated if it’s a style issue)**

**Comment by YuriSizov** [comment]
We now have a link in the sidebar, courtesy of @Calinou
