### ISSUE TITLE
Not enough contrast on footer sitemap

### ISSUE THREAD

**Issue by afk-mario** [godotengine/godot-website#407]
**Operating system, Browser, Browser Version:**
Linux
Firefox 103.0b8

**Issue description:**
The footer `<strong>` elements don't have enough contrast.

**Screenshots (greatly appreciated if it’s a style issue)**

![image](https://user-images.githubusercontent.com/1025751/179101876-3dccc547-91f7-48fa-aefc-7936fef878a8.png)

**Comment by Calinou** [comment]
I can confirm this on Chromium 100 (light theme). Clearing the cache doesn't fix the issue. The dark theme is unaffected though.

cc @YuriSizov
