### ISSUE TITLE
Add links to next and previous news articles

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#419]
When reading individual Godot news articles (e.g. those linked to from https://godotengine.org/news/), it would be nice if there were links to the next and previous articles.

So for example, in the [Godot and consoles, all you need to know](https://godotengine.org/article/godot-consoles-all-you-need-know) article, there would be links at the bottom to [Release candidate: Godot 3.4.5 RC 1](https://godotengine.org/article/release-candidate-godot-3-4-5-rc-1) and [Dev snapshot: Godot 4.0 alpha 12](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-12).

This would allow someone to read articles in order, without having to keep pressing Back and then picking the next article. This would be most useful to someone who wants to catch up with a lot of Godot news (e.g. someone new to the engine).

Hopefully this is something the CMS can do for you - I'm not suggesting you manually add all the links!

See for example the site https://retrostuff.org/2021/09/27/sega-pico-flash-cart-adapter-v2/ which does this.

Thanks.

**Comment by Alex-Reynolds** [comment]
I am part of a team for a university class, we would like to attempt to add this feature.

**Comment by YuriSizov** [comment]
@Alex-Reynolds Well, nobody else is working on it yet. But we will probably work on an update to the page overall, which might incorporate something like that.

Feature-wise, it's probably more useful to display relevant news (using the tagging/category system, perhaps) than just next and previous news.

**Comment by Alex-Reynolds** [comment]
We don't require our PR to be merged. Hopefully our effort can help with an update though!

**Comment by coppolaemilio** [comment]
I think adding the next and previous links could be a nice first step, and it can later on be improved to be the recommendation based on topics that @YuriSizov describes.
Good luck with the PR!

**Comment by nsundriyal62** [comment]
i don't think it still resolve, can i work on this issue ?

**Comment by Calinou** [comment]
Yes :slightly_smiling_face: 

The website now uses a static site generator (Jekyll), instead of a CMS (Winter). This will change *how* you should implement the feature, but it's still feasible.

**Comment by nsundriyal62** [comment]
ok

i have a plenty beginner knowedge of jekyll and still learing it 

so i can resolve it


thanks man
