### ISSUE TITLE
Add a news section to the homepage

### ISSUE THREAD

**Issue by vybr** [godotengine/godot-website#42]
I think the homepage should have a news section at the top of it. It makes it easier to see what's new with the engine without having to always click on the news page and also makes the page look more "active".

**Screenshots (greatly appreciated if it’s a style issue)**
[Example of what I mean](https://i.imgur.com/1wMeK8k.png)

**Comment by djrm** [comment]
im still thinking on the best way to add this, will arrive soon.

**Comment by akien-mga** [comment]
I agree we need this, currently the only way to notice new articles is to visit the News page manually, or use RSS.

**Comment by djrm** [comment]
soon is a relative term, 512ebd976dd980ffee48a847f65b9c8135d2b752
