### ISSUE TITLE
Replace the website's banner with a slideshow

### ISSUE THREAD

**Issue by BenjaminNavarro** [godotengine/godot-website#422]
I've been consulting Godot's website for years and, it might be me, but I have the impression that the TailQuest banner has always been there. Showing just a single game might give the impression to people that Godot was only used to make that game, which would be a shame considering all the other games published, or about to at least.

What I suggest is to remove this fixed banner and replace it with a slideshow of selected games that would better convey to people what can be done with the engine (2D, 3D, desktop, mobile, AR/VR, tools, ...).

Since selecting the games to display can be time consuming I propose to always take the ones from the latest showreel since the selection has already been made and that they would best reflect what's currently done with Godot. The order should be randomized on each page load to not favor one game in particular.

Each slide would have:
 - A screenshot representative of the game
 - The name of the game and its developer/studio
 - The platforms the game is (will be) released on, probably as some form of tag list or icons

The slides could be clickable too and link to the developer website, steam page, etc.

**Comment by YuriSizov** [comment]
Yes, that's in the plans.

**Comment by Calinou** [comment]
I'm not fond of automatically spinning carousels for a few reasons:

- They are heavy on resources on low-power machines, such as phones and low-end laptops (which are common among Godot users). Having a website that feels slow is counterproductive, even if it looks "prettier".
- Their autoplaying nature is not friendly towards people with ADHD. The `prefers-reduced-motion` hint can be used to disable the animation for users whose browsers request it, but this option isn't well known among users yet.

Instead, I would prefer we rotate the image on every patch release (like Blender does), or serve a random image based on some criteria (e.g. weekday or time of day).

> The order should be randomized on each page load to not favor one game in particular.

Randomizing on each page load isn't cache-friendly, hence my above suggestions for using more cache-friendly criteria :slightly_smiling_face:

**Comment by fire** [comment]
I second @Calinou 's proposal to rotate it every patch version.

**Comment by coppolaemilio** [comment]
Having an image per patch would be great to also use the same "identity" on social media and other announcements. I like the idea 👍

**Comment by cbirdsong** [comment]
Here is a good blog post listing many reasons carousels are not a good idea, along with supporting links: https://jhalabi.com/blog/carousels-no-one-likes-you

**Comment by BenjaminNavarro** [comment]
Yes I guess you're right. I recently had to remake a website and the slideshow was one of the thing that had to go because of mobile (un)friendliness. I'm not a webdev so these things were not obvious for me beforehand.

I guess I can close the issue, especially since there are already plans for improving this part of the website.
