### ISSUE TITLE
Blog posts source?

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#423]
Hi. Are the source files for the blog posts available in a repo, so we could send PRs? Or if not, could they be? I often spot little typos and would love to scratch the itch of correcting them!

**Comment by YuriSizov** [comment]
No, blog posts are stored in the CMS. We can fix typos if you point at them wherever you want (as an issue here, as comments on social, as a message on rocket chat, etc).

**Comment by JohnVeness** [comment]
OK, thanks for the quick reply. I once did a year of proofreading another website's blog without CMS access and it was extremely tedious doing the "in the third paragraph, second sentence, third word should be 'dog'" kind of thing! So I don't fancy repeating that, and I guess I will just have to grit my teeth. Thanks anyway :)

**Comment by YuriSizov** [comment]
Oh, there is definitely no point in fixing typos or bad English in old posts. But if you see a mistake in a fresh post, feel free to poke us.

PS. Btw, that's how we review things internally anyway :) A couple dozen people can read the post before it is posted and we try to get feedback and fix everything we can spot, and it often boils down to "this in that section is wrong, should be XYZ". 🙃

**Comment by JohnVeness** [comment]
I'm just wondering if this has now changed with the site rewrite? Are PRs now possible for blog article corrections?

**Comment by YuriSizov** [comment]
Yes, you can open PRs to fix typos now.
