### ISSUE TITLE
Add download button for re-added 'server' Linux platform

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#43]
**Issue description:**
Godot 3.0.1 was just released and comes with a `linux_server_64` build: http://downloads.tuxfamily.org/godotengine/3.0.1/Godot_v3.0.1-stable_linux_server.64.zip

It should be added to the [download page](https://godotengine.org/download/linux), probably as a third option for Linux.

**Comment by djrm** [comment]
closed by 39d461701f74387a549260dd60b464418db9b57c
