### ISSUE TITLE
Allow CDN caching

### ISSUE THREAD

**Issue by bits-by-brandon** [godotengine/godot-website#434]
Although the site is behind Cloudflare, it seems the cache control headers are set to not cache, which prevents the CDN from doing its job.

The site should allow caching so the CDN can help prevent new posts from taking down the site

Headers related to caching are:
`pragma` `cache-control` and `expires`

**Comment by tylerritchie** [comment]
Currently, Winter returns the session in a `Set-Cookie` header which is contributing to Cloudflare not caching:

> Cloudflare does not cache the resource if the `Cache-Control` header is set to `private`, `no-store`, `no-cache`, or `max-age=0` _or if there is a cookie in the response._ [1] [emphasis added]

Apache could be configured to set `Cache-Control` with `public, max-age=300` (or whatever appropriate cache length), and unset pragma and other headers contributing to caching. And then Cloudflare could be configured to cache when `Set-Cookie` is present [2] or we could un-set `Set-Cookie` with Apache. Both of the latter two would need to be excluded from the admin routes and both approaches break the unpublished article functionality without other workarounds.  

Either (or both) of the above approaches seem like possible short-term options.

Getting a caching plugin working (or writing a thin middleware to do the same) would be a nicer long-term approach and a nice balance of:
- still supporting article previews
- being portable outside of apache/cloudflare

Quicksilver [3] looks like it could serve as either a good drop-in (with flat file caching for serving up higher-volume traffic outside the context of a CDN) or a decent pattern to follow as it has a straightforward middleware [4].

[1] https://developers.cloudflare.com/cache/about/default-cache-behavior/
[2] https://developers.cloudflare.com/cache/about/cache-control/
[3] https://gitlab.biz-mark.ru/free-plugins/Quicksilver/
[4] https://gitlab.biz-mark.ru/free-plugins/Quicksilver/-/blob/master/classes/middlewares/QuicksilverMiddleware.php

**Comment by coppolaemilio** [comment]
This should be working properly now with the new setup. If there is anything missing I can reopen.
