### ISSUE TITLE
Press kit and Logo download and usage guidelines

### ISSUE THREAD

**Issue by djrm** [godotengine/godot-website#44]
Adding a presskit page and logo download and usage guidelines would be good to make a more standarized image of the engine + having a centralized place for such content so that journalist and content creators can get it easily.

pring @akien-mga

**Comment by mhilbrunner** [comment]
There is a .zip with some files that were already prepared in https://github.com/godotengine/godot/issues/8514

**Comment by fire** [comment]
Tasks from the other issue.

-  Logo usage guidelines
-  Engine screenshots
-  Game/showcase screenshots
-  Info text
-  Add to website
-  Color codes

**Comment by fire** [comment]
@Calinou Is there any steps blocked here?

**Comment by Calinou** [comment]
@fire I think we could update @diowonderland's press kit, upload it to the website files then reference it on some page. (I'd prefer not committing a ZIP to the godot-website repository.)

**Comment by fire** [comment]
Thoughts on making a pull request and putting the assets in:

godot-website/themes/godotengine/assets/press_kit

Then we can write some text to reference it? Or use a presskit style markdown generator.

**Comment by fire** [comment]
Made a PR.

https://github.com/godotengine/godot-website/pull/153
