### ISSUE TITLE
Filled vs outline circle difference

### ISSUE THREAD

**Issue by gejza74** [godotengine/godot-website#440]
**Operating system, Browser, Browser Version:**
Debian Bullseye, Firefox 102.3.0esr
Target: Android

**Issue description:**
Circle filled vs circle outline, they draw not on the same place!
This bug occurs in Godot version 3.4.4, 3.5.0, 3.5.1 too, probably earlier versions also affected.

Draw outline circle produce not the same result as draw filled circle. It looks like the outline circle position is double value of the filled circle.
Expected: they must draw on the same position.

**Screenshots (greatly appreciated if it’s a style issue)**
![1](https://user-images.githubusercontent.com/25371290/193184234-cf88e027-2395-4c5e-88ca-5e804fb0ad2e.png)
![2](https://user-images.githubusercontent.com/25371290/193184238-61e8affb-0493-4a65-a1b8-1a34db303948.png)
![3](https://user-images.githubusercontent.com/25371290/193184240-b3182469-3946-48dd-aada-bdfef7d4b740.png)
![4](https://user-images.githubusercontent.com/25371290/193184243-bb071976-7bf2-4169-82cc-cf4bdf6bea47.png)
![5](https://user-images.githubusercontent.com/25371290/193184245-b55e59d9-51ee-4d57-a085-9e10822452f3.png)

**Comment by gejza74** [comment]
Sorry, it was early morning yet, I see now, it goes into the "godot website" issues, not into "godot engine" self.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/66647.
