### ISSUE TITLE
Look into providing an Atom feed additionally to the RSS one

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#458]
We currently provide a RSS feed for the blog articles: https://godotengine.org/rss.xml

I'm not too familiar with the differences between the two, but we may want to consider also providing an Atom feed for those who prefer.

This came up in a discussion here: https://mastodon.gamedev.place/@Pinky/109365008217454027
With the aim to provide both summary/excerpt and full contents of blog posts, which seems to be possible with Atom but maybe not with RSS? (at least if https://en.wikipedia.org/wiki/RSS#RSS_compared_with_Atom is accurate, we might want to look further into the RSS spec to see if it can include a summary/abstract too).

**Comment by bits-by-brandon** [comment]
Looks like there isn't a separate summary field separate from content in RSS, so having the full post in the description might be the only way to include all the content in RSS, although it doesn't look like that's really what it's for https://www.rssboard.org/rss-specification

**Comment by coppolaemilio** [comment]
Done with: https://github.com/godotengine/godot-website/commit/f0fbb33db10168e42df26a43525eca832f443464

Just a couple years of delay, but here it is: https://godotengine.org/atom.xml 

:)
