### ISSUE TITLE
Add Mastodon card to Community page next to Twitter

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#459]
Title says it all.

**Comment by YuriSizov** [comment]
Do you have a suggestion for a description? CC @coppolaemilio

**Comment by coppolaemilio** [comment]
Get small bits of development news without Elon's shenanigans. 👀 

I'll think about something! haha


Edit: Connect with us in the Fediverse

**Comment by YuriSizov** [comment]
Just noting that we would also need a screenshot of the account
