### ISSUE TITLE
The current theme doesn't have a 404 page

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot-website#469]
The website currently displays the default 404 page from the CMS:
![image](https://user-images.githubusercontent.com/2206700/204062772-1fb33133-aad5-45e0-b3e2-8ec931055afc.png)

We should make a proper 404 page that shows a search input to potentially redirect them to where they want to go (in case the page was moved) or some links to places that might be of interest: news, events or linking to our social media pages.

**Comment by Calinou** [comment]
There used to be a custom 404 page, but it was removed as it caused an issue with the CMS: https://github.com/godotengine/godot-website/pull/190

**Comment by coppolaemilio** [comment]
I'll investigate the issue and see if I can find a solution. What was to issue exactly? I don't really understand the description on the PR

**Comment by YuriSizov** [comment]
Perhaps the issue was with loading sub-pages without a full reload?
