### ISSUE TITLE
Improve style of code font in articles

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#48]
**Operating system, Browser, Browser Version:**
Mageia 6 x86_64, Firefox Nightly (from today)

**Issue description:**
The code font takes too much horizontal space IMO, with extraneous padding on the sides and too much space between letters:

![screenshot_20180324_191626](https://user-images.githubusercontent.com/4701338/37867387-d9b69c7c-2f97-11e8-8221-317b2e755c81.png)
![screenshot_20180324_191604](https://user-images.githubusercontent.com/4701338/37867384-cd324992-2f97-11e8-9397-3a94bae43532.png)

I'd suggest to try to remove the extraneous padding on the sides so that it fits better inline, and if possible make it more compact by reducing the padding between letters (if that can't be done, maybe reducing the font size a bit wouldn't be too bad).

**Comment by djrm** [comment]
yeah, the padding needs to be fixed, but the letter spacing should not be moved, this is a monospace font, so it is natural that it is wider, narrowing it could make it look bad under certain conditions (like text that includes 'm').

**Comment by MHillier98** [comment]
Is there any real reason for there being padding at all? IMO, it looks better without any:
![image](https://user-images.githubusercontent.com/26564949/54475322-0af03080-4844-11e9-957a-024ad8ed399e.png)

I couldn't find any other examples of the `<code>` tag being used, except for the page that @akien-mga mentioned above, which is the blog post [GLES2 and GDNative, progress report #3](https://godotengine.org/article/gles2-and-gdnative-progress-report-3).

**Comment by akien-mga** [comment]
It's used in a handful of other blog posts, mostly devblogs or some of the 3.0.x maintenance release notes. I'm fine with having the padding removed if you can make a PR :)
