### ISSUE TITLE
Impossible to sign up for chat.godotengine.org

### ISSUE THREAD

**Issue by Welteam** [godotengine/godot-website#487]
First, sorry for this out of place issue but I found no appropriate way to report this and I felt an issue was needed at this point (see below).

**Issue description:**

Title is explicit, here is what I know. All this happened on Nov 29, more than 2 weeks ago:
+ I tried to use an existing account to access the contributor chat but forgot the password so I asked for an email through the "Forgot Password?" functionality. I never received the email
+ Thinking it was an issue with the provider, I created a new account with an email address from a different provider but never received the account verification email. I concluded there was an issue with the system and it blocked email sign up. I decided it was important to report it
+ As I found no relevant tracker for this issue on github, I thought I would try to contact the administrators through another channel so I went to the matrix chat. There two things happened: 
1. Bengtsts, a matrix moderator, confirmed the issue on his side and reported that signing up with github sso did not work either. This mean the issue may be broader than expected
2. @Calinou noticed our exchange and told me he is a chat admin but doesn't have access to the server. He said he would report the issue to the right persons (TMM/hpvb according to him) but to not expect a quick resolution as they are very busy. Things stopped there

Sadly, two weeks later, the issue is still here. It's not an issue in itself but Calinou doesn't seem to have logged back to matrix since then and did not reply to my ping so I have no visibility on the state of things. 
I hope to use this issue to bring more eyes to the problem and gather feedback.

**Comment by hpvb** [comment]
My apologies I completely forgot about this. This has been fixed now:

![image](https://user-images.githubusercontent.com/2591099/208239049-f40906d8-42eb-46e7-a7e6-aa4d498a9ab8.png)
