### ISSUE TITLE
https://godotengine.org/ gives me error 500

### ISSUE THREAD

**Issue by rafrafek** [godotengine/godot-website#488]
**Operating system, Browser, Browser Version:**
MacOS Ventura 13.0.1
Latest Safari, Firefox, Chrome

**Issue description:**

Visiting https://godotengine.org/ gives me error:

Internal server error

Godot Engine Error
We're sorry, but an internal server error occurred when trying to display this page.
[Go to the homepage](https://godotengine.org/)

**Screenshots (greatly appreciated if it’s a style issue)**

<img width="1755" alt="image" src="https://user-images.githubusercontent.com/23004737/207644297-3da66cec-4910-4a41-a531-450b71fac2cf.png">

**Comment by rafrafek** [comment]
It started to work, thanks!

**Comment by YuriSizov** [comment]
Yep, sorry, I broke some stuff, but it's all fixed now <3
