### ISSUE TITLE
Main page Latest news unreadable due to transparency overlay 

### ISSUE THREAD

**Issue by besh81** [godotengine/godot-website#492]
**Operating system, Browser, Browser Version:**
Win10 - Firefox 108.0 64bit

**Issue description:**
Scrolling down the main page the "Latest news" section becomes unreadable

**Screenshots (greatly appreciated if it’s a style issue)**
![Cattura](https://user-images.githubusercontent.com/16460595/207802025-7a8cdf0b-3138-4c6f-84d3-bc667724fdab.JPG)

**Comment by YuriSizov** [comment]
That shouldn't happen unless you have an outdated asset cached by your browser. Try pressing <kbd>Ctrl + Shift + R</kbd> to reload the page without the browser cache.

**Comment by besh81** [comment]
You're right. 
Ciao
