### ISSUE TITLE
i18n issue with footer text

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-website#497]
https://github.com/godotengine/godot-website/blob/b7c48d0cea8bd6e61624cbd7401c7acb0624fd63/themes/godotengine/partials/footer.htm#L12-L13

This creates these two entries in the POT:

* Godot is a member of the
* Kindly hosted by

There are two issues:

1. The order of words is fixed:
    e.g. "Godot is a member of the X" will be something like "Godot is X's member" when localized in Chinese.
2. The period at the end of the sentence can't be localized.
    e.g. Chinese & Japanese uses `。` instead of `.`

It'll be great if this part can use some placeholders like in the engine code, e.g. `TR("Godot is a member of the %s.")`.

p.s. The sentence above also have this issue, the words are broken apart:

https://github.com/godotengine/godot-website/blob/b7c48d0cea8bd6e61624cbd7401c7acb0624fd63/themes/godotengine/partials/footer.htm#L11

**Comment by YuriSizov** [comment]
Yep, this is known, but we've decided to do it this way for now. We will have to replace this, and maybe some others, with proper strings with placeholders at some point.

**Comment by Bholanath8436** [comment]
I want to work on this issue, please assign me this issue.

**Comment by YuriSizov** [comment]
@Bholanath8436 Sorry, there is nothing to work on here at the moment. We don't have a decided upon solution for these cases yet.

**Comment by coppolaemilio** [comment]
I'm closing this one since it refers to the previous CMS and not the current static site. Hope we can bring back i18n soon!
