### ISSUE TITLE
Broken HTML in "Godot Editor running in a web browser" page

### ISSUE THREAD

**Issue by spookyvision** [godotengine/godot-website#498]
**Operating system, Browser, Browser Version:** n/a

**Issue description:** [Godot Editor running in a web browser](https://godotengine.org/article/godot-editor-running-web-browser) has a malformed href here (missing quotation mark at the end):
`a Godot Editor prototype running in browsers is being presented at <a href="https://godotengine.org/>this address</a>`

**Screenshots (greatly appreciated if it’s a style issue)**
![image](https://user-images.githubusercontent.com/45840/209484282-cbdb91d2-f555-488c-84a1-8f77ed339a7a.png)

**Comment by coppolaemilio** [comment]
Thank you for the report. There seems to be an issue with the markdown parser in that particular combination of bold + link text combination. 
I replaced the style and added a note since the link referenced in that part is a 404 now.
