### ISSUE TITLE
Updating the CMS plugins

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#5]
We need to update our CMS plugins to their latest versions. Here are the versions we currently ship:
![image](https://user-images.githubusercontent.com/4701338/30417885-832c8ada-9931-11e7-866b-ec3e393bcbd0.png)

AFAIK, @alketii modified some of those plugins to better fit our needs, so we need to compare our current plugin code to the original upstream code of our versions to generate patches that we could reapply, or better, find a way to achieve our use cases without modifying the plugin code. (Or if we need to modify plugins, try to get our changes upstreamed).

**Comment by akien-mga** [comment]
See also #4.

**Comment by akien-mga** [comment]
I'm not sure if we use the Wysiwyg Editors and BBcode plugins, and we most likely don't need the October Demo plugin either, so maybe we could get rid of those?

**Comment by akien-mga** [comment]
I confirm that we're not using the Wysiwyg Editors (and their BBcode extension) anywhere: 
![image](https://user-images.githubusercontent.com/4701338/30418674-0fe517c4-9934-11e7-80f9-a3fd74f93ab4.png)

I don't think we need WYSIWYG to edit HTML/CSS, nor for the blog plugin where the Markdown editor is just fine, so I'd say let's get rid of it. Less plugins == less risks of security issues.

**Comment by pcvonz** [comment]
Here is a diff of the blog plugin from what was present in the rainlab blog repos and what is currently in our repos. Looks like the components are the only thing changed, which should be easy address. 
[blog.txt](https://github.com/godotengine/website/files/1322898/blog.txt)

**Comment by pcvonz** [comment]
Here is a diff of the portfolio plugin. Seems to be only a one line change. 
[portfolio.txt](https://github.com/godotengine/website/files/1322925/portfolio.txt)

**Comment by pcvonz** [comment]
Commit 076b8399e7 will make it safe to update the blog plugin. I put the changes made to the `blogPost` and `blogPosts` component straight into the `home` and `article` layout.
 All that needs to be addressed is the portfolio plugin. 

The portfolio plugin hasn't had any updates since we installed it and as I've mentioned the change is only on one line. Updating my local version of October doesn't overwrite the change. Even if it did, it'd be a small and non breaking bug (the showcase would display games starting with the first added to the last added). That could be fixed very easily.

**Comment by akien-mga** [comment]
> I'm not sure if we use the Wysiwyg Editors and BBcode plugins, and we most likely don't need the October Demo plugin either, so maybe we could get rid of those?

Done with 1258657.

> Commit 076b839 will make it safe to update the blog plugin. I put the changes made to the blogPost and blogPosts component straight into the home and article layout.

Awesome. I've now updated the blog plugin to the latest version in 254fe00.

For the portfolio plugin, as mentioned above, there's no update so nothing to do for now. We may discuss in #7 if we want to do more customizations to it, given that upstream is not really active.
