### ISSUE TITLE
Label Mono download as alpha

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#50]
**Operating system, Browser, Browser Version:**
All.

**Issue description:**
The current download page doesn't make it clear that the Mono build is alpha software and does not reflect the overall stability of the non-Mono Godot 3.0.2.
![screenshot_20180412_105144](https://user-images.githubusercontent.com/4701338/38666555-7e0a65c8-3e3f-11e8-85a7-82375f959bb9.png)

It would be nice to make it crystal clear so that users know about it before they download and try to run it (especially since it might very well crash if they don't have the correct Mono SDK installed).

**Comment by Zerokami** [comment]
Right. I downloaded Mono version thinking it works and then got warning message and compile errors.

**Comment by aaronfranke** [comment]
This is still relevant for Godot 3.1. It could be called "Mono & C# Version (Experimental)".

**Comment by MHillier98** [comment]
Would `"Mono Version (C# Support - Alpha)"`, be appropriate, @akien-mga, or does @aaronfranke's description work better?

**Comment by akien-mga** [comment]
I wouldn't call it experimental, but alpha is fine yes.

**Comment by MHillier98** [comment]
Is this something that should be fixed, or should we just leave it as is?

**Comment by Calinou** [comment]
I think we should leave it mostly as-is right now, though we might want to add a note that the Mono version doesn't support *reliably* exporting to HTML5 yet (due to missing AOT compilation support).

**Comment by akien-mga** [comment]
I guess two years later this is less relevant indeed.

The Mono version is starting to be fairly stable and we'll soon promote it to "beta" once iOS support is in the stable build, so we can probably leave things as is.
