### ISSUE TITLE
https://godotengine.org is marked as "Not secure". 

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot-website#51]
Not sure if it is appropriate to post this as an issue here, but since we have no dedicated sysdev/ops section;

The SSL Certificate seem to be out of date, although I have no personal experience with SSL certification and HTTPS to know for sure. "Not secure". 
![](https://i.imgur.com/VT1Vhrs.png)
![](https://i.imgur.com/LM4Z44x.png)

Using Comodo Dragon browser.

**Comment by akien-mga** [comment]
I can't reproduce it in Firefox Nightly:
![screenshot_20180413_065757](https://user-images.githubusercontent.com/4701338/38717574-001d2dae-3ee8-11e8-9d9d-e041bd6742eb.png)

Nor Chromium 62.0.3202.94:
![screenshot_20180413_065916](https://user-images.githubusercontent.com/4701338/38717603-2f44a92c-3ee8-11e8-89c0-126b482d69a2.png)

So I guess your browser has an outdated certificates bundle.

**Comment by akien-mga** [comment]
Still can't reproduce, so I assume it's a user-specific issue (either due to the certificates bundle used by your browser, or by your proxy if any).
