### ISSUE TITLE
Include full articles content in RSS feed

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#52]
**Operating system, Browser, Browser Version:**
All, not relevant.

**Issue description:**
Our current [RSS feed](https://godotengine.org/rss.xml) only includes the excerpt of the blog articles.
[Some users](https://twitter.com/JohnHamiltonNZ/status/990602312962916352) would like to have the full contents to be able to read them in their RSS reader.

Our RSS is generated via the `sobored.rss` plugin: https://github.com/godotengine/godot-website/tree/master/plugins/sobored/rss
This is likely the default configuration, I don't know yet if it can easily be configured differently, or if we need to patch the plugin.

**Screenshot:**
![screenshot_20180429_182745](https://user-images.githubusercontent.com/4701338/39408724-03d7d692-4bdb-11e8-86b2-329491135fda.png)

**Comment by akien-mga** [comment]
Well that was easy, it can indeed be configured:
![screenshot_20180429_182650](https://user-images.githubusercontent.com/4701338/39408714-e73c02d8-4bda-11e8-93d5-5766bdc3b189.png)

![screenshot_20180429_182714](https://user-images.githubusercontent.com/4701338/39408718-f13047b8-4bda-11e8-9877-d58ba0949512.png)

**Comment by ronroniv** [comment]
Looks like this change somehow made RSS feed to give wrong URLs to articles.

For instance it gave this link for the article about 2D skeleton:
https://godotengine.org/news/godot-gets-2d-skeletal-deform

When the correct URL is this:
https://godotengine.org/article/godot-gets-2d-skeletal-deform

**Comment by akien-mga** [comment]
Thanks, it should now be fixed too.
