### ISSUE TITLE
Deploy cover image generator to our hosting

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#520]
We've been enjoying a little tool made by @bits-by-brandon for making cover images for many blogposts in recent months. Here it is:

https://github.com/bits-by-brandon/godot-image-generator
_(hosted at https://godot-image-generator.vercel.app/thumbnail)_

Currently it is hosted externally, which means it can potentially disappear one day and we won't be able to use it. Self-hosting it should be a good way to protect against that, since it's a custom solution and adaptable to our needs as necessary. Currently it relies on Puppeteer, which can be a bit of a burden, having to download a whole Chromium executable, so perhaps we could rewrite it to use a more low-level solution for rendering the final image. It can even be client-side, made with canvas, though that means it can look differently depending on the user's browser.

Something to explore for sure, but also not too important, if we can't make it work for now. Simply deploying it to our platform would be a good first step anyway. We have some gigabytes to share.

**Comment by adamscott** [comment]
Fixed since the fork of [YuriSizov/godot-website-cover-generator](https://github.com/YuriSizov/godot-website-cover-generator) to [godotengine/godot-website-cover-generator](https://github.com/godotengine/godot-website-cover-generator).

**Comment by YuriSizov** [comment]
I could have transferred the ownership...

**Comment by adamscott** [comment]
@YuriSizov If you want to, yes! I can delete the fork.

**Comment by YuriSizov** [comment]
> If you want to, yes! I can delete the fork.

I'm fine either way, but do note that you have issues disabled right now, because it's a fork and my repo is technically "upstream".

**Comment by akien-mga** [comment]
> > If you want to, yes! I can delete the fork.
> 
> I'm fine either way, but do note that you have issues disabled right now, because it's a fork and my repo is technically "upstream".

Yes transfering your repo would be better indeed.

I deleted the fork, could you transfer your repo to the @godotengine org?

**Comment by YuriSizov** [comment]
@akien-mga So it turns out, to transfer to an org you need to have create repo permissions. But I can transfer to other users, with a confirmation on the other side (no idea why this is not a thing for orgs). So I did the next best thing and transferred it to you, check your inbox!

**Comment by akien-mga** [comment]
Got it, thanks!

And deflected it further to https://github.com/godotengine/godot-website-cover-generator in a brilliant poll billiard shot :D
