### ISSUE TITLE
Update this repo's About info

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#521]
A small thing, but this repo's "About" info still references OctoberCMS.
![image](https://user-images.githubusercontent.com/2512915/212697223-d93dd327-3f52-434e-b255-86bd511adbaa.png)

**Comment by coppolaemilio** [comment]
Thanks for the latest reports @JohnVeness !

![image](https://user-images.githubusercontent.com/2206700/212702196-2f411f82-7da1-4448-b2a5-74da304d6b3c.png)

Made some updates, feedback is welcome :)
