### ISSUE TITLE
Incorrect forwarding from godotengine.org/news/ leads to godotengine.org/https://godotengine.org/blog

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot-website#527]
It looks like when moving https://godotengine.org/news/ to https://godotengine.org/blog/ the forwarding has been set up incorrectly, so https://godotengine.org/news/ now send you to https://godotengine.org/https://godotengine.org/blog which is just a 404 error.

**Comment by YuriSizov** [comment]
Hmm, it used to work correctly.

**Comment by lostminds** [comment]
Yeah, I don't know when this appeared, but I noticed it today as I tried to enter https://godotengine.org/news/ since this was in my browser URL field history, and I ended up in the wrong place. So I guess at least quite recently https://godotengine.org/news/ worked.

**Comment by devofnull** [comment]
Can confirm, my bookmark redirects the same way.

**Comment by coppolaemilio** [comment]
It seems like a forward slash is being added to the redirect template:
```
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="/https://godotengine.org/blog">
  <script>location="/https://godotengine.org/blog"</script>
  <meta http-equiv="refresh" content="0; url=/https://godotengine.org/blog">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="/https://godotengine.org/blog">Click here if you are not redirected.</a>
</html>
```

I'll see if I can create a custom redirect template.

**Comment by devofnull** [comment]
> It seems like a forward slash is being added to the redirect template:
> 
> ```
> <!DOCTYPE html>
> <html lang="en-US">
>   <meta charset="utf-8">
>   <title>Redirecting&hellip;</title>
>   <link rel="canonical" href="/https://godotengine.org/blog">
>   <script>location="/https://godotengine.org/blog"</script>
>   <meta http-equiv="refresh" content="0; url=/https://godotengine.org/blog">
>   <meta name="robots" content="noindex">
>   <h1>Redirecting&hellip;</h1>
>   <a href="/https://godotengine.org/blog">Click here if you are not redirected.</a>
> </html>
> ```
> 
> I'll see if I can create a custom redirect template.

Rather than a forward slash being added, it looks like the template expects a relative link and someone put in a full link. I image repeating the same process but typing in just "blog" instead of "domain/blog" will have the desired result.

**Comment by coppolaemilio** [comment]
Those files are being generated by a plugin: https://github.com/jekyll/jekyll-redirect-from
And we did no changes to it, so not sure where the forward slash is coming from.
From our end we add the redirects on the front-matter of the pages like so:

```
redirect_from:
  - /devblog/index.html
  - /news/index.html
  ```
