### ISSUE TITLE
Add a link to weblate

### ISSUE THREAD

**Issue by omicron321** [godotengine/godot-website#53]
A link to https://hosted.weblate.org/engage/godot-engine/ could be now added to https://godotengine.org/community page!

**Comment by MHillier98** [comment]
This should probably be addressed, nearly a year later. I'd be happy to add this :)

It might also be worth updating some other screenshots?

**Comment by Calinou** [comment]
I don't see Weblate as a community resource (one won't interact with other Godot users there), but rather as a developer/contributor resource. By the way, it's already mentioned in the [Introduction](https://docs.godotengine.org/en/latest/about/introduction.html#about-the-documentation) page in the documentation.

**Comment by MHillier98** [comment]
Fair enough then, that seems reasonable. Would there be a better place somewhere else to link it, so there can be more awareness brought to it?

**Comment by omicron321** [comment]
> I don't see Weblate as a community resource (one won't interact with other Godot users there), but rather as a developer/contributor resource. By the way, it's already mentioned in the [Introduction](https://docs.godotengine.org/en/latest/about/introduction.html#about-the-documentation) page in the documentation.

like github which is referenced there
community is users + devs + contributors

**Comment by akien-mga** [comment]
We now have a call to action + Weblate widget and links on the landing page of the documentation: https://docs.godotengine.org/en/latest/index.html

As well as the Introduction page as mentioned earlier.

IMO that's good enough. I do agree with Calinou that Weblate is not a "community platform" to the same extent as the other ones listed. GitHub is different, there's an issue tracker where lots of discussions happen, so the community interacts there. Weblate doesn't allow much interaction within the community apart from comments on specific strings - which is actually a problem we need to solve as translators for a given language need to better coordinate their work and conventions.

**Comment by Calinou** [comment]
For future reference, see also https://github.com/godotengine/godot/issues/33547.
