### ISSUE TITLE
Add item author to rss feed

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#532]
Please can you add author names to items in the rss feed? I believe the correct tag is dc:creator, but I'm not an expert.

**Comment by coppolaemilio** [comment]
We'll look into it 👍

**Comment by coppolaemilio** [comment]
I tried Feedly and I can identify a couple things we could improve, not a priority right now but I'll work on it for sure.

**Comment by moonLight-7k** [comment]
I am excited to contribute to this open source project and look forward to working with the community to improve and advance the project

**Comment by moonLight-7k** [comment]
Hello, I am interested in contributing to open source projects and would love to participate in any that you have available. I have experience in web Development and am eager to learn and grow my skills through working on these projects. Please let me know if there are any opportunities for me to get involved, I would greatly appreciate it. Thank you!

**Comment by YuriSizov** [comment]
Feel free to open a PR if know how to address this issue!

**Comment by moonLight-7k** [comment]
Well we'll eventually find it out
