### ISSUE TITLE
Add a notice at the top of the article page for outdated articles

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot-website#534]
Our blog can sometimes be treated as a knowledge base because several features have been historically documented there (before being ported to the docs, or instead of that). So old articles sometimes appear as relevant search results in web searches, or are shared throughout the community, while the information in them keeps getting out of date.

While we could go through each article manually and update it, it would make sense to add a general notice to every article older than XX months that it may be potentially outdated. We can probably skip the release notes with that.

As the website is only updated with builds, we could make that notice appear with some JS, but I think it's also okay to update it periodically through new deploys when we publish stuff. We do it regularly enough to refresh old pages in time.

**Comment by merumelu** [comment]
Like this?
![ScreenShot](https://user-images.githubusercontent.com/17676847/213568936-b0bf6707-348b-43ad-9dc7-f58de49bf9bf.png)
For now the implementation uses an (autogenerated) `site.outdated_article_threshold` variable that is calculated as  `build_time - one_year`. While things in Godot can sometimes change quickly, a year seems like a good indicator that something is "old".

**Comment by Calinou** [comment]
> While things in Godot can sometimes change quickly, a year seems like a good indicator that something is "old".

Looks good, but the 12 month threshold might be a bit too strict; I'd make the threshold for displaying the warning 18 months. As of writing, a 18-month threshold means that articles published before July 2021 would have a warning, while a 12-month threshold would apply this to articles published before January 2022.

Also, the box should have a yellow background to make it stand out more.

**Comment by coppolaemilio** [comment]
There's a reference here of a similar box here: 
![Clipboard - January 19, 2023 4_43 AM](https://user-images.githubusercontent.com/2206700/213674618-bec80eb8-773e-4882-bb8b-4169ea2b23f6.png)

and another one here:

![image](https://user-images.githubusercontent.com/2206700/213732353-c05e7a71-572e-4a72-87fa-29cde4eed5d0.png)


Like Calinou said, a yellow background could work, and it would be nice to have an extra field on the front matter in case we want to specify some custom text relating to that specific article. 

For instance, if we see a lot of visits to an article that has a more recent version, we could go in the old one and add a link to the new one inside that disclaimer box.
