### ISSUE TITLE
Scrollbars don't follow user's theme preference

### ISSUE THREAD

**Issue by silmarillion1337** [godotengine/godot-website#547]
![image](https://user-images.githubusercontent.com/73029407/215750881-b2eb4412-c6f0-4950-b5e9-03408687589f.png)

Scrollbar is light themed when the rest of the website is dark themed.

Can be fixed by setting the [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#adapting_to_color_schemes) property of `:root`:
```
:root {
  color-scheme: light dark;
}
```

**Comment by Aadijindal07** [comment]
Hi @silmarillion1337 this might work and actually am new to contribution, gsoc etc can you guide me am good in solving problem but no one is assigning me i dont know why

This will set the overall color scheme of the website to a combination of light and dark colors. You can also set the color scheme specifically for the scrollbar using CSS, like this:

::-webkit-scrollbar {
width: 12px;
background-color: #333333;
}

::-webkit-scrollbar-thumb {
background-color: #f2f2f2;
border-radius: 10px;
}

The above code sets the width of the scrollbar to 12px, with a dark background color, and a light-colored thumb (the part that you drag to scroll).

You can adjust the colors and width to match your desired design and color scheme.


hopefully it help you i also use same scrollbar for my websites

**Comment by Aadijindal07** [comment]
Hi @silmarillion1337 @Calinou  i would love to solve this problem kindly assign this to me It is very simple and something i also came across few time back

**Comment by Calinou** [comment]
@Aadijindal07 For future reference, we only use the assignees feature for core contributors (and we don't always use it in the first place). Since contributors can leave at any time for any reason, we'd rather avoid a situation where nobody is working on an issue because it's assigned to someone who is no longer active.

In other words, you can open a pull request directly :slightly_smiling_face:

**Comment by Aadijindal07** [comment]
hi @Calinou i am new to all these things i am good programmer know how to solve problems this one is a simple one you just need to add this code 

body::-webkit-scrollbar {
   width: 0.5em;
   background-color: #F5F5F5;
   border-radius: 10px;
}
 
body::-webkit-scrollbar-thumb {
  background-color: #000000;
  border-radius: 10px;
  box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
 
body::-webkit-scrollbar-thumb:hover {
  background-color: #555;
  box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
}

I had just added a little bit styling if you didnt like it just remove it

actually I want to crack gsoc as it will improve my profile for university and i just know how to code i dont know how to like use this shitty github can you guide me little bit how to like crack gsoc , by the way i am very good with web if anyother thing you want from me i will be very happy to solve it

**Comment by YuriSizov** [comment]
The OP here has a suggestion for a native solution. It should be enough. Using vendor specific CSS to style the scrollbars is not going to work, as not all vendors support the same level of customization.

**Comment by Aadijindal07** [comment]
@YuriSizov what if we use a javascript library perfect-scrollbar 

import PerfectScrollbar from 'perfect-scrollbar';
const container = document.querySelector('.scrollable-container');
const scrollbar = new PerfectScrollbar(container);


const scrollbar = new PerfectScrollbar(container, {
  thumbMinSize: 20,
  background: '#F5F5F5',
  thumbColor: '#000000',
});

**Comment by silmarillion1337** [comment]
@Aadijindal07 that would be overkill, just make a PR that sets `color-scheme` property of `:root` in the global CSS file (not familiar with Jekyll, so you'll have to figure that out).

**Comment by YuriSizov** [comment]
Not only would that be an overkill as mentioned above, it is generally not a good idea to replace the main page scroll with a JavaScript solution. It's fine for other in-page scrolls, but the main scroll should be native.

**Comment by Ymanawat** [comment]
@YuriSizov @Calinou  I Resolved the issue and created a pull request, kindly review it.
