### ISSUE TITLE
Broken RSS

### ISSUE THREAD

**Issue by omnipotenti** [godotengine/godot-website#548]
![Untitled](https://user-images.githubusercontent.com/124082378/216040324-d6b63847-6e35-4632-9e29-1c438b217c20.png)

Hello! 

The RSS newsfeed stopped working.

(I've never described bugs before, so I apologize for my rambling description.)
Regards

**Comment by githubtaxi** [comment]
dublicate

**Comment by coppolaemilio** [comment]
I pushed another fix for this. Seems to be fixed when you open https://godotengine.org/rss.xml on Firefox
