### ISSUE TITLE
Showcase link broken

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot-website#56]
## https://godotengine.org/showcase/2

- Colony Strikes Back - The Game

## https://godotengine.org/showcase/3

- Galactic Void 2
- Color Flex

## https://godotengine.org/showcase/4

- The Orbit
- Save the Bubble
- Pineapple Runner

## https://godotengine.org/showcase/5

- Desert Kingdom Defense
- Sawdust
- Fox Hunting
- Squane

## https://godotengine.org/showcase/6

- SAG - Space Adventure Game
- Links Fusion
- Tap Gym

## https://godotengine.org/showcase/7

- Dots & Dots
- Bounce
- Push Pin Solitaire
- Sushi Simulator

## https://godotengine.org/showcase/8

- Top
- Circle Invasion
- Circl
- World Flags Challenge
- Quad-Teleport Square Puzzle
- Frog

## https://godotengine.org/showcase/9

- Numbers Fusion
- Beware the Cat

## https://godotengine.org/showcase/10

- Space Protector
- Rain Drop
- Bounce It

**Comment by akien-mga** [comment]
Seems like all Google Play games, so I guess it's due to Google removing all apps without a privacy policy which use (or seem to use, via Godot's placeholders #18192) user data permissions.

**Comment by ObaniGemini** [comment]
### https://godotengine.org/showcase/2
- Neon Bounce

also is broken :)

**Comment by akien-mga** [comment]
Instructions to fix the issue: https://godotengine.org/article/fixing-godot-games-published-google-play

**Comment by Calinou** [comment]
The showcase was removed in https://github.com/godotengine/godot-website/commit/1806dd90be0d280a293c5c70b2fbde9a2237653b, making this issue obsolete. Closing.
