### ISSUE TITLE
Add console deploy into features

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot-website#57]
We all know godot can export to xbox one, play station 4 and nintendo switch via third parties. But it is not stated in the website.

**Comment by Zerokami** [comment]
@Juankz Can you post links to the thrid parties that have release source for this? Or do you mean third parties have done it, so, it's possible?

If it's the 2nd, it shouldn't be added.

**Comment by Juankz** [comment]
https://godot.readthedocs.io/en/3.0/tutorials/platform/consoles.html

Doesn't apply?

**Comment by Zerokami** [comment]
@Juankz That link states that it is not possible to port to console directly.

`Godot does not officially support consoles (save for XBox One via UWP) currently.`

`Console ports of Godot are offered via third party companies (which have ported Godot on their own) and offer porting and publishing services of your games to consoles.`

 But some people have written code to make it possible and they charge for it.

So, Godot officially doesn't support console ports. And unless you pay these people or write code that makes it possible to export to consoles yourself it is not going to work.

It seems you can export to Xbox one using UWP though.

**Comment by Juankz** [comment]
Well **not officially** but it **is possible** through third companies. I mean, in my opinion is worth mentioning it on the website. But if general agreement is that it is not, then no problem, we can close this.

**Comment by vnen** [comment]
I think it's okay to mention that it is provided commercially by third-party companies. If this is clearly stated it's not a problem, it's not like we're leading people on.

**Comment by Calinou** [comment]
This was done in https://github.com/godotengine/godot-website/pull/134, closing.
