### ISSUE TITLE
Add Android editor on Google Play to Download page

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#571]
We now distribute the Android editor officially on Google Play:

https://play.google.com/store/apps/details?id=org.godotengine.editor.v3
https://play.google.com/store/apps/details?id=org.godotengine.editor.v4

For our Download page, we should probably promote this one as the main download option (but still give access to the APK on TuxFamily for those who don't use/want to use Google Play).

We might want to make room for a future F-Droid distribution we'd want to link to as an option.

CC @m4gr3d

**Comment by YuriSizov** [comment]
> We might want to make room for a future F-Droid distribution we'd want to link to as an option.

It can go into the All downloads section, I think. And for the top I think the Play Store version as our main, and the APK download as a secondary. Should be easy to do.
