### ISSUE TITLE
Add a link to itch.io on the Download page

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#58]
Someone suggested to add a link to https://godotengine.itch.io/godot below the Steam download link, so that people can download the engine from there as well.

**Comment by Zerokami** [comment]
This is Good since Ithc.io allows downloads without Login.

Also AFAIK it doesn't spy and send to cloud about things like how long you have been using a Software or Playing a game unlike Steam.

**Comment by akien-mga** [comment]
Fixed by 92400e6bcf.
