### ISSUE TITLE
Blog page wrong layout on page change

### ISSUE THREAD

**Issue by Fr0sk** [godotengine/godot-website#584]
The blog page appears with a different layout when changing pages.

This is how it appears when opening the Blog page:
![image](https://user-images.githubusercontent.com/5650342/222477074-16636369-6557-4506-8eed-c3b4de3ed826.png)

This is how it appears when selecting the 2nd page:
![image](https://user-images.githubusercontent.com/5650342/222477217-07bdf96f-7bd1-46b7-8ada-63666aae0d63.png)

It also happens when selecting the 1st page. Pressing the View Original button returns the proper view.

**Comment by YuriSizov** [comment]
Which operating system and which browser are you using? Do you have JavaScript disabled? Do you have an adblocker? Anything else we must know about your system configuration?

**Comment by Calinou** [comment]
Which web browser are you using?

It looks like reader mode is enabled by your web browser. Look at the address bar at the top of the window; you should be able to disable it there.

**Comment by coppolaemilio** [comment]
This is clearly not our code, it is the browser of the client. I'm closing but feel free to re-open.

**Comment by Fr0sk** [comment]
Sorry about the delay in the response, for some reason my email client skipped notifications from Github emails... 

The browser was Brave, testing in Chrome does work as intended, so I also would assume it is some reading mode in the browser being activated as Calinou said. I also apologize for the false positive. Thank you for your time :)

**Comment by coppolaemilio** [comment]
No worries, thanks for the report!
