### ISSUE TITLE
Opening the 4.0 web editor shows list of files instead of the editor

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot-website#588]
### Steps to reproduce

Go to [godotengine.org/download](https://godotengine.org/download) and scroll down to all platforms. Select the web editor.
It will take you to [editor.godotengine.org/releases/4.0.stable](https://editor.godotengine.org/releases/4.0.stable/).

You will see a list of files instead of the editor page. The editor can be loaded by opening `godot.editor.html` manually.

### Possible Fix

As Calinou mentioned on rocket chat, the file should be manually renamed to `index.html` after deployment.

**Comment by Ni-011** [comment]
Hey, can you tell me how to join the rocket chat group of godot you are talking about? I'd like to discuss about this bug

**Comment by YuriSizov** [comment]
@NitinRana01125532553 Contributors chat is at https://chat.godotengine.org. You can ask questions about website in the `#website` channel. You can also ask questions here.

**Comment by YuriSizov** [comment]
Fixed with ecf00234eec08da8a8ca1d526db993f583279bde.
