### ISSUE TITLE
Godot 3.5.1 uses Mono, but the download link mentions .NET

### ISSUE THREAD

**Issue by TheVeryStarlk** [godotengine/godot-website#591]
# Steps to reproduce
The [download page](https://godotengine.org/download/3.x/windows/) has a .NET option which is incorrect for Godot 3.5.1; As it uses Mono instead.

![image](https://user-images.githubusercontent.com/45287860/222935384-d71a7757-c01c-436f-b9ed-2df6edcff797.png)

# Expected behavior
The [download page](https://godotengine.org/download/3.x/windows/) should be corrected to Mono.

![image](https://user-images.githubusercontent.com/45287860/222935424-5735f109-593c-4da4-99f9-7516ecd17a29.png)

**Comment by YuriSizov** [comment]
Mono is a .NET runtime, it's not incorrect. The Mono dependency is explained in the Requirements section.
