### ISSUE TITLE
The RSS feed is broken

### ISSUE THREAD

**Issue by omnipotenti** [godotengine/godot-website#595]
Hello, there!

![godot_rss](https://user-images.githubusercontent.com/124082378/223705555-7a6b0312-40ef-46db-9b4a-7f237ca240d5.jpg)

Error: XML Parsing Error: not well-formed
Location: https://godotengine.org/rss.xml (Line Number 13, Column 17)
Browser: Mozilla Firefox 109.0 (64-bit)

Best regards!

**Comment by YuriSizov** [comment]
Thanks! Should be fixed now.
