### ISSUE TITLE
Enhancements to "More" menu

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#6]
Here's how it looks like currently:
![image](https://user-images.githubusercontent.com/4701338/30419073-6818be72-9935-11e7-8bbd-3361a0df9b52.png)

- The "Donate" link should be changed to be themed like the rest, it no longer makes sense to have it different from the others
- I'd propose to change the order of links to: Q&A, Asset Library, Devblog, Events, Donate, Contact
- Maybe we can add the so-far unreferenced License page there too, let's say between Events and Donate

Of course a more in-depth overhaul of the menu sections might be sensible, but it can be discussed further in #3. The points in this issue are meant to be easy to fix right now.

**Comment by pcvonz** [comment]
Updated the More menu to address all the issues. I also took away the active class from the devblog item since none of the other items use it.
