### ISSUE TITLE
Add links to avatar images to /rss.xml

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-website#606]
I'm working on https://github.com/noidexe/godot-version-manager a version and project manager for Godot. One of it's features is showing a preview of the Godot blog in timeline format:
![image](https://user-images.githubusercontent.com/526829/228650786-ac1f47e5-1cf2-484b-92bc-b7352e3a0fa5.png)

Right now I have implemented a sort of DOM/Jquery using XMLParser to parse the html returned by /blog and display the news, but that of course can break any time you change the structure of the document. I was talking about this to Emilio during GDC and I've just noticed the new rss feed has exactly what I want. The old one was a large download with every blog post and didn't contain snippets but the new one is just what I need.
The only thing missing is avatar image urls so if you could add that it'd be awesome. Right now the only author info is `<dc:creator>Author Name</dc:creator>`. Is there any endpoint where I can use that to get an avatar url?

**Comment by YuriSizov** [comment]
You can try downloading https://github.com/godotengine/godot-website/blob/master/_data/authors.yml, names should map exactly to the `name` key, and the link in there should be accessible from the main domain.

I'm not sure if RSS/Atom has a field for author avatars, but if there is, we can of course add it.

**Comment by noidexe** [comment]
Thanks! I think that will work
