### ISSUE TITLE
Add a json feed version of /rss.xml

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot-website#607]
I'm working on a "Godot Version Manager" and there are other similar projects doing the same, having a timeline view of /blog as a feature. 

Right now the only way to parse xml is using XMLParser which is pretty low level and I've heard it's going to be deprecated in Godot 4. Json is much easier to handle within GDscript and there is https://www.jsonfeed.org/ which is similar to RSS/Atom.

Would it be posible to offer the same info in json feed format?

**Comment by YuriSizov** [comment]
> Would it be posible to offer the same info in json feed format?

Yes, we can add anything we want, it's all templated. [Here's the RSS source](https://github.com/godotengine/godot-website/blob/master/pages/rss.xml), for example.

**Comment by noidexe** [comment]
Thanks. I'll see if I can contribute that myself then

**Comment by bits-by-brandon** [comment]
@noidexe would the [JSON Feed](https://www.jsonfeed.org/version/1/) format work for you?

**Comment by coppolaemilio** [comment]
@noidexe can you review https://github.com/godotengine/godot-website/pull/649 ?

**Comment by noidexe** [comment]
Looks perfect. It has all the info I was currently scraping from the html. Thanks!

**Comment by coppolaemilio** [comment]
Closed by #649
