### ISSUE TITLE
Godot website downloads 3.5 instead of 4

### ISSUE THREAD

**Issue by adam-cyclones** [godotengine/godot-website#609]
### Godot version

N/A

### System information

Linux

### Issue description

When on Linux, I visit the download page to get a copy of 4.x and it downloads a build of 3.x

I had to go into the downloads repository to got a copy instead

### Steps to reproduce

Try it out and check the about Godot 

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Which page are you visiting, and where are you visiting it from? What button do you press, where did you get the link, etc?

**Comment by adam-cyclones** [comment]
https://godotengine.org/

[Download latest][4.0.1]

**Comment by YuriSizov** [comment]
It's downloading 4.0.1.

**Comment by adam-cyclones** [comment]
Could it be that the binary is launching my already installed 3.5 instead?

**Comment by YuriSizov** [comment]
That's not how executables work, generally. The one that you launch is the one that gets launched. How do you launch it? Do you use a shortcut somewhere, or do you click on the downloaded file directly?

**Comment by adam-cyclones** [comment]
I was mistaken, sorry for wasting time
