### ISSUE TITLE
Home page refers to GDNative but not GDExtension

### ISSUE THREAD

**Issue by ttmc** [godotengine/godot-website#610]
The following card is on the Godot website home page as of today:

![Screenshot from 2023-03-30 16-04-31](https://user-images.githubusercontent.com/1210951/228974341-ba941481-865f-44e9-b2c8-f57b66fe7f91.png)

As you see, it refers to GDNative but not its successor, GDExtension. I guess that both are going to be in use, for now, so maybe mention both?

Here's a link to the source:

https://github.com/godotengine/godot-website/blob/55e1bd3730a1e5be3ff7895b5ed1af72051cf519/pages/home.html#L316

**Comment by Calinou** [comment]
Godot 3.x only supports GDNative, but Godot 4.x only supports GDExtension. They provide an equivalent feature (use native libraies, which lets you use other programming languages).

I suggest we only mention GDExtension in the description.
