### ISSUE TITLE
Add Godot User Group Berlin

### ISSUE THREAD

**Issue by mtttz** [godotengine/godot-website#612]
Hello,
we are a new Godot User Group recently founded. Could you please add us to the overview of Godot User Groups?
https://godotengine.org/community/user-groups/

Here are the details:

Type: Physical community
Name: Godot User Group Berlin
Map Marker Location: xHain hack+makespace, Grünberger Str. 16, 10243 Berlin, Germany
Country: Germany
Meetup: https://www.meetup.com/godot-user-group-berlin/
Mastodon: https://mastodon.gamedev.place/@GodotUserGroupBerlin
Discord: https://discord.gg/Sm3CgrqqQa

Thank you very much and grettings from Berlin

Matteo

**Comment by YuriSizov** [comment]
Feel free to open a PR editing this file: https://github.com/godotengine/godot-website/blob/master/_data/communities.yml

**Comment by mtttz** [comment]
Will do! I was looking for the source of the data before but could not find it, thanks! 🚀 👍
