### ISSUE TITLE
[ethical request] - rename 'linux' tab to 'GNU/Linux'

### ISSUE THREAD

**Issue by kacperpaczos** [godotengine/godot-website#63]
I think that 'Linux' tab should be rename to 'GNU/Linux' tab. It is very important.
https://www.youtube.com/watch?v=kb2T8hWRu8g
![obraz](https://user-images.githubusercontent.com/23406555/44286785-a13a8480-a26a-11e8-9029-509b81b5ed52.png)

**Comment by akien-mga** [comment]
We use "Linux" everywhere knowingly, so no.
