### ISSUE TITLE
Website origin server is down

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot-website#648]
The website's origin server is currently down. Cloudflare is currently serving a cached version:

![Screenshot from 2023-06-04 18-02-12](https://github.com/godotengine/godot-website/assets/4892574/3cb5f0bf-e211-4617-8bf3-e72797e6c346)

Clicking 'refresh' yields the 521:

![Screenshot from 2023-06-04 18-02-18](https://github.com/godotengine/godot-website/assets/4892574/ac8f344d-57ff-4d77-b99e-ba4ad7a07f86)

**Comment by YuriSizov** [comment]
Yes, there is nothing we can do. It's a hosting problem.

**Comment by bits-by-brandon** [comment]
@YuriSizov @coppolaemilio  Is there anything I can help with to help migrate to another provider?

**Comment by bits-by-brandon** [comment]
If Vercel is an option for hosting providers, seems like hosting Jekyll is super easy to do. I spun up my fork of the site at https://godot-website.vercel.app/ to test. Seems to work pretty well.

**Comment by coppolaemilio** [comment]
Our current issue is that the Asset Library is a PHP site that lives at `godotengine.org/asset-library/`. So we can't really move the whole thing to a static hosting until we don't split the asset lib to a proper subdomain.

We would also need to be able to restore the current database.

**Comment by YuriSizov** [comment]
We have actually complete a move to a new hosting platform for both the main website and the asset library. Only QA remains on the old hosting for technical reasons. But we should experience better stability going forward.
