### ISSUE TITLE
markdown leaking into news summary

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot-website#65]
The page at https://godotengine.org/news displays summaries of the news stories.
These summaries can expose raw markdown.

![image](https://user-images.githubusercontent.com/1151394/46155364-b531c700-c2a9-11e8-9dc5-7f28c50cf6f1.png)

> Welcoming our new gold sponsor: ImageCampus
> By: Juan Linietsky Sep 21 - 2018
> Godot gets a new Gold sponsor! In this case, we are welcoming \[Image Campus](https:\/\/www.imagecampus.edu.ar), an education institution located in Buenos Aires, Argentina, which specializes in animation, digital art and videogames.

**Comment by akien-mga** [comment]
Fixed (article authors should not use Markdown for the abstract).
