### ISSUE TITLE
Links to other websites in article briefing on the News page are not properly displayed

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot-website#66]
**Operating system, Browser, Browser Version:**
Windows 10: Chrome, Edge

**Issue description:**
When viewing the articles on the [News](https://godotengine.org/news) page, links formatted like `[name](link)` are not properly displayed. (check the screenshot below)

**Screenshots**
![cc_2018-10-03-14-02-30-9035819](https://user-images.githubusercontent.com/26509794/46409313-635bc780-c715-11e8-90dc-33b02738c736.png)

**Comment by akien-mga** [comment]
Fixed (article authors should not use Markdown for the abstract).
