### ISSUE TITLE
ask.godotengine.org is down

### ISSUE THREAD

**Issue by notjak0** [godotengine/godot-website#673]
## The title says it all. 
# Cloudflare says it's a problem with the host, meaning that there is a problem with the servers themselves.

**Comment by YuriSizov** [comment]
Yes, there is an issue with the hosting platform since at least last Sunday.

**Comment by maximstewart** [comment]
Any ETA or what's going on??

**Comment by Calinou** [comment]
> Any ETA or what's going on??

See https://www.tuxfamily.org/en/news/2023070900. We have no control over the current situation, and no ETA either.

**Comment by YuriSizov** [comment]
Note that we are moving away from TuxFamily, but to do that we need it to come online first. It's likely that shortly after it does come online, we will disable the Q&A platform to perform the migration.

**Comment by michelcastilho** [comment]
https://ask.godotengine.org/114682/godot-4-setget-with-export

I was trying to access this URL and this came up

![image](https://github.com/godotengine/godot-website/assets/40428897/77f2cd8d-fb01-4a00-b6f3-84efe1862f51)

The ask platform is returning this message, but other users report that they could access the same URL with no issues.

**Comment by YuriSizov** [comment]
Godot Q&A has been migrated to the new hosting so these downtimes should no longer be an issue, or at least we would be able to do something about them quicker and easier.

The platform is still in the read-only mode as we need to work on some internal things with it. But it's up and accessible!
