### ISSUE TITLE
Sound or image bug after a couple of queue_free() and add_child() on the same node in 3.5.2

### ISSUE THREAD

**Issue by DomestiqueBaston** [godotengine/godot-website#699]
Hello,

Audiostreamplayers don't work after I queue_free() then add_child for the second time. Here's the code:

`extends Node2D

const SceneTwo = preload("res://SCENES/TMP/SceneTEST.tscn")
const SceneDeath = preload("res://SCENES/SCREENS/Death.tscn")

func _process(_delta):
	if Input.is_action_just_pressed("ui_cancel") and not Autoload.transition_signal:
		Autoload.time_before_death = 25.0
		Autoload.time_to_die = false
		$Transition_Overlay/Sprite.take_screenshot()
		$Active_Scene.get_child(0).queue_free()
		$Active_Scene.add_child(SceneTwo.instance())
	if Input.is_action_just_pressed("ui_cancel") and Autoload.transition_signal:
		Autoload.transition_signal = false
		var _useless = get_tree().reload_current_scene() #"var _useless = " to silent Godot
	if Autoload.transition_signal:
		$Transition_Overlay.hide()
	if Autoload.time_to_die:
		$Active_Scene.get_child(0).queue_free()
		$Active_Scene.add_child(SceneDeath.instance())
		Autoload.transition_signal = false`

Here's the scene:

![image](https://github.com/godotengine/godot-website/assets/97660855/09eab325-ec97-4a96-8df7-fb01dadc86df)

When I put a breaking point at the line `$Active_Scene.add_child(SceneDeath.instance())` (just before the end of the code) and resume the execution then the sound is playing OK but the animated image is like frozen. Without the breaking point, the sound plays very, very slowly but the image seems OK. I'm a beginner so maybe I'm just doing something wrong but some people told me to send a bug report so here I am.

DB.

P.S. : using GODOT 3.5.2 on Windows 10 and Linux Mint 21.2 Cinnamon

**Comment by YuriSizov** [comment]
Hey there! This is a repository for the Godot website, not for the engine itself. You want to open an issue in the main project repository: https://github.com/godotengine/godot. Please make sure to follow the issue template and provide all the necessary information for contributors to be able to reproduce your issue.

**Comment by DomestiqueBaston** [comment]
Oops! Sorry.

DB
