### ISSUE TITLE
Improve sorting of Showcase entries

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#7]
The [Showcase](https://godotengine.org/showcase) page (Portfolio plugin in the backend) is currently a bit rough, and we have no control on the sorting of the submitted entries. They are sorted in reverse chronological order (from latest addition to oldest one).

That means that we don't have much control over *what* we actually show on the main page, and since we've been relatively flexible with what kind of games get added to the database (basically as long as it looks decent visually, it's fine), at some times we might be showing low-to-mid quality mobile games instead of more impressive desktop titles, for example.

I'm open to suggestions on how to improve this.

Here's the idea I have so far:
- Split the page vertically in two sections:
  * The first section would have games which were tagged by webmasters with the ["featured" tag](https://godotengine.org/showcase/tags/featured)
  * The second section (below) would have all other games
- Both sections would be randomized, so that you see different games each time you load the page
- Instead of a pagination, we could have the following:
  * The first section (featured) would be a one-row banner that can be scrolled to the left and right, showing more entries
  * The second section would be scrollable vertically and new entries would load as you scroll down

WDYT?

**Comment by pcvonz** [comment]
I think those are great ideas, and would be pretty easy to implement. 
How do we currently accept entries? Is it just by hand? Would it be worth the effort to add the ability to accepts entries?

**Comment by menip** [comment]
3.0 is released, and this really needs to be addressed. 

Two sections is the way to go, but they would be toggle-able instead of both visible. What I mean is near top center of showcase page you would be able to select either "Featured" *or* "All", to switch to respective view modes. At that point, the page can have more entries appear as you scroll down. 

We should also put together some guidelines as to what will be considered for "Featured", preferably something more specific than "need to have nice graphics".

**Comment by Veragalz** [comment]
I feel your second option is more modern, as it is seen more and more in modern web design. Here's a more detailed idea of what I think the second option should be like:

- The top banner functions as a big, flashy showcase. Anything shown here is required to have a well made gif either showing off gameplay or cinematics, and the banner autoscrolls between maybe 5 or 10 games after the end of each gif. The Game Title is displayed on the bottom left side of the gift, and a tool for users to manually select the "page" they are on is on the bottom left, with dots for each entry.

Example: 
![image](https://user-images.githubusercontent.com/15857782/35773415-49888882-0917-11e8-9983-9bdb3d850dc1.png)
- There is pretty much not much to be said about the second section, except for that tiles should vary in size and shape and have a :hover action that maybe darkens or blurs the image. Each tile is simply the name of the game in front of an image of the game, with optionally the games genre in small text.

- Games in the second section should be sorted based on some sort of popularity measure, be it rating or downloads. You would likely have to scrub the various websites these items are on for rating info. It should not be random. I saw 5 fidget spinner games early on while looking in the current showcase area, this is where you present your products capabilities and showing just any games can potentially lead to a false assumption about your engine's worth.

I really do hope you incorporate some of these ideas. 🙂

**Comment by Zephilinox** [comment]
It seems the new layout has done away with tags being displayed, though you can still filter by them manually by going to the right url e.g. (https://godotengine.org/showcase/tags/mobile)

bringing tags back so they can be displayed and adding tags for the games marketplace (steam/itch) would do a lot to help, or at the very least adding a desktop tag so we can filter out all of these mobile games.

**Comment by djrm** [comment]
the current showcase is temporal, because the plugin needs to be changes or something to make it possible to query featured + standard games, and yes i also want a featured section on top (like the one i proposed months ago in the new website issue)

**Comment by danboid** [comment]
I'm v.happy with godot 3, but I think the showcase page really needs some work, as this ticket is discussing.

In addition to improved filtering and display of the games, I would also like to be able to see at a glance which games are open source and whether they are 2.x or 3.x projects, at least for the FOSS games.

I think FOSS games should be highlighted on the showcase page due to their potential educational value to those learning godot and godot users/devs looking for inspiration or guidance.

**Comment by danboid** [comment]
Rather than stating free or non free, I'd rather showcase entries show the license of the software alongside the version of godot it uses. We could use a catchall like 'Commercial' for non free / closed source games if the license is unknown or not a commonly used one.

**Comment by Juankz** [comment]
Hello everybody!

@DavidAmado and I have experience with web development and would like to help with this long awaited issue.

I have read the comments above and here are some mockups I made on the frontend side:

For the featured games a near fullscreen image will cause huge impact. Let 2 buttons switch between all and featured.

![desktopshowcaseft](https://user-images.githubusercontent.com/18577412/45912029-e1989f80-bde0-11e8-8f5d-3d7cc9d3225e.jpg)
![mobileshowcaseft](https://user-images.githubusercontent.com/18577412/45912007-a4341200-bde0-11e8-8577-7bcc17e57dda.jpg)

For all the entries better stick with the cards layout, i added rating, but we should talk about how to validate votes that rate such entries and what "five stars", "four stars" really mean.

![desktopshowcaseall](https://user-images.githubusercontent.com/18577412/45912016-c168e080-bde0-11e8-805e-b2df46234fc1.jpg)
![mobileshowcaseall](https://user-images.githubusercontent.com/18577412/45912014-bdd55980-bde0-11e8-9b5e-f77b94408be1.jpg)

This is it so far. What do you think?

PS. Mockups were made using draw.io. Here is the file if you want to do some modification and contribute to the discusion: 
[GodotMockups.zip](https://github.com/godotengine/godot-website/files/2407420/GodotMockups.zip)

**Comment by Zephilinox** [comment]
I don't think ratings are appropriate, too many issues with it. It looks like you have a favourite icon (the heart) on there too, which doesn't seem like it would work too well as there's no login system, so just storing it in cookies?

I like that there is a featured showcase. Featured games should be required to have some kind of accompanying write up by the creator about their use of godot and more details about the game, like Unity (https://unity.com/madewith/cuphead)

There should be stricter requirements for the aspect ratio of the thumbnails submitted, the varying sizes look awful on the current showcase.

Font sizes on desktop are currently way too big, not sure about mobile.

Store availability should be added (Steam/Itch), Price (Free/Paid or maybe FOSS/Commercial), and License (MIT/GPL/Closed Source, etc)

Somewhere to see the video showcase like https://www.youtube.com/watch?v=ZR1Yfmr1KRM, and perhaps even being able to add videos as an alternative to thumbnails.

**Comment by Juankz** [comment]
The hearth button was "up-vote", this is to measure popularity. Authentication could be done with Github and/or social media. I would rather remove the five stars rating and leave the number of votes (like scketchfab does).

Commercial/FOSS is a good filter. I don't think price should be added. The site is not a store and prices change all the time (promotions, sequels, etc). I'm also not sure if license should be displayed, wouldn't it be enough with Commercial/FOSS filter?

So more mockups:

![desktopshowcaseallv2](https://user-images.githubusercontent.com/18577412/45934636-66f98c80-bf66-11e8-89b2-818a40b7f1ce.jpg)

![mobileshowcaseallv2](https://user-images.githubusercontent.com/18577412/45934637-6cef6d80-bf66-11e8-9fa6-bb2625c7b74e.jpg)

Featured write up. For mobile is pretty straightforward so no picture.

![godotproposaldesktopwriteup](https://user-images.githubusercontent.com/18577412/45934638-71b42180-bf66-11e8-9801-9fcba5ccf27b.jpg)

**Comment by Juankz** [comment]
No more discussion? I sincerely would like to know what @akien-mga and @djrm think about this since you made the changes for Godot 3 launch

**Comment by flurick** [comment]
It would be cool to be able to search for tagged features in games to see how others implemented them and have us all share, inspire and build on each others ideas more. I would like to suggest a page for submitting searchable tags to projects (somewhat like how a wiki might work)

**Comment by nikhilCad** [comment]
Is nothing going to be done about it. This issue was opened literally 2 years ago and nothing has been done about it. It is driving new users away.

**Comment by Calinou** [comment]
@nikhilCad As we don't have time and resources to maintain a dynamic showcase page, we'll likely replace the showcase tab with a static page that embeds videos such as the [April 2019 Desktop/Console games showreel](https://www.youtube.com/watch?v=NlKEO1N8wMM).
