### ISSUE TITLE
Differentiate the Linux headless and server builds

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#70]
Many people are wondering what is the difference between headless and server builds, so it should be clarified on the download page.

Alternatively, the Linux server build could be part of the export templates, which means there would no longer be a download button for it. In this case, dedicated servers would be created by exporting projects.

**Comment by fire** [comment]
My understanding is the headless is a headless editor build, while the server build is an export template. Maybe that distinction helps.

**Comment by akien-mga** [comment]
Fixed by fa3d5945.
