### ISSUE TITLE
Matrix Community links to https://matrix.to/#/#godot:feneas.org but https://www.feneas.org/ says "The domain name feneas.org Is for sale!"

### ISSUE THREAD

**Issue by mogoh** [godotengine/godot-website#705]
This does not seam right.

**Comment by testman42** [comment]
Noticed this some time ago as well.
Any idea who to talk to about this?
There is Godot matrix space that contains some relevant rooms: https://matrix.to/#/#godot-space:matrix.org
( also https://view.matrix.org/?query=godot )
[Git Blame](https://github.com/godotengine/godot-website/blame/master/pages/community/community.html#L285) for the feneas.org room seems to be from 8 months ago.
We could make a PR with a link to a working room or space, provided we can agree on one.
