### ISSUE TITLE
Download button on Godot Fund Navbar leads to Windows version instead of host platform

### ISSUE THREAD

**Issue by deanrih** [godotengine/godot-website#710]
I noticed a small inconsistency that the download button from the navbar on the `fund.godotengine.org` always leads to the Windows version of the download (`godotengine.org/download/windows`) regardless of the current host OS, the download navbar button on the main/home page, features, blog, community and about (contact) page is correct.

**Comment by YuriSizov** [comment]
Funding page is separate from the main website, but it does borrow the layout from it. On the main website we also hardcode the windows link for no specific reason, but it gets overwritten on the client with JavaScript to match the platform (it's marked with `set-os-download-url`). A similar trick can be ported to the funding website, or alternatively it can use just `/download`, which should redirect you appropriately as well.

**Comment by deanrih** [comment]
Ah I see, I agree that it should be in the same URL instead and then the javascript decides the download page of the OS (still with the option to change, of course) instead by URL like /windows, I like the Blender (https://www.blender.org/download/) approach better, which is the same mechanism to what we are discussing currently.

**Comment by JohnVeness** [comment]
Is the source for fund.godotengine.org available?

**Comment by YuriSizov** [comment]
No, it's a private repository

**Comment by coppolaemilio** [comment]
Thanks for the report! 
Issue should be fixed now. It might take a minute for the cache to clear, but it will get there eventually.
