### ISSUE TITLE
"Godot 3 also supports glTF 2.0 and OBJ" on Download pages

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#713]
On the various Download pages, there is the text "Godot 3 also supports glTF 2.0 and OBJ". I was wondering if we could drop the "3" from that now, assuming 4 still supports those?

**Comment by YuriSizov** [comment]
Can you give us a link of one such page?

Edit: Oh, you mean for the Blender ESCN exporter? I think we're ought to just remove it, though there were some attempts to revive the plugin.

**Comment by Calinou** [comment]
> Edit: Oh, you mean for the Blender ESCN exporter? I think we're ought to just remove it, though there were some attempts to revive the plugin.

I would prefer removing it from the page as well, as it's unmaintained.
