### ISSUE TITLE
Fund Credits: Some sponsor images are cut off on iPhone

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot-website#718]
![IMG_2767](https://github.com/godotengine/godot-website/assets/17506573/a3a0814b-b06b-4a2f-b5a8-3d22a02709f4)

At the default zoom level on iPhone 13 Pro Safari, some sponsor images (specifically Re-Logic) are cut off.

**Comment by coppolaemilio** [comment]
Thanks for the report! I pushed a temporary fix, but I'll need to eventually rewrite this part because of the wildly different sizes of logos we get. Closing for now.
