### ISSUE TITLE
Change references to the "Twitter" to "X"

### ISSUE THREAD

**Issue by MIfoodie** [godotengine/godot-website#722]
Problem: things such as the footer (see below) still use the old Twitter logo.

![image](https://github.com/godotengine/godot-website/assets/94649676/142e4a2c-ba71-4d01-99a2-c60e07b245c8)

Also on the "Community" page it still says Twitter.

![image](https://github.com/godotengine/godot-website/assets/94649676/a76cbcb2-e9f0-49fe-8aa7-f264039906e1)

**Comment by coppolaemilio** [comment]
Thanks for the report! 
The brand recognition that Twitter has is nowhere near the same as the new name. Changing this will probably create more confusion than anything else. If you check most websites around they are still using the Twitter logo/name to refer to that social media platform. Once this change is present in most sites I think it would be a good moment to update ours, but hopefully by that time, someone else would have bought the platform and return the name it should always have had. 

Unity's site footer:
<img width="220" alt="image" src="https://github.com/godotengine/godot-website/assets/2206700/65e46aca-65e8-46d4-8916-25a4e88c15cf">
Epic's site footer:
<img width="220" alt="image" src="https://github.com/godotengine/godot-website/assets/2206700/7390ec4a-9cdd-4ba9-8581-1c98766fbfa1">
Game Maker's site:
<img width="199" alt="image" src="https://github.com/godotengine/godot-website/assets/2206700/0ec7f839-b1aa-47e0-90c7-52b334139059">
Eurogamer: 
<img width="300" alt="image" src="https://github.com/godotengine/godot-website/assets/2206700/4a8e7916-79c2-48b5-b7c3-b298615f60ba">

And the list goes on...

Hope that makes sense. Closing this for now, but feel free to reopen it or continue commenting if you don't agree. Cheers!
