### ISSUE TITLE
https://ask.godotengine.org/ returns 404

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-website#727]
![image](https://github.com/godotengine/godot-website/assets/114925991/d7f978d6-16fc-47ec-a3e4-4f42ae1019ca)

i navigated to it from https://godotengine.org/community/

**Comment by JohnVeness** [comment]
See #673

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-website/issues/673.
