### ISSUE TITLE
Also available on Steam card hard to read on hover

### ISSUE THREAD

**Issue by rxlecky** [godotengine/godot-website#75]
**Page:**
https://godotengine.org/download/

**Issue description:**
On downloads page, hovering over `Also available on Steam` card causes the text turn dark grey which makes it very hard to read on the dark blue background.

**Screenshots**
![obrazok](https://user-images.githubusercontent.com/35656626/52911843-c8b9ea80-32a9-11e9-92db-fcba802a9096.png)
_Before hover_

![obrazok](https://user-images.githubusercontent.com/35656626/52911849-f0a94e00-32a9-11e9-8cf5-620e75027362.png)
_After hover_

**Comment by akien-mga** [comment]
Indeed. While fixing this, it could be good to add a similar link for itch.io too: https://godotengine.itch.io/godot

**Comment by akien-mga** [comment]
> While fixing this, it could be good to add a similar link for itch.io too: https://godotengine.itch.io/godot

Actually that's part of #59.

**Comment by MHillier98** [comment]
Would it be better to use the accent colour for the link? Or should it be white for the button, and accent only being used for a link?

I also think the buttons would look better without a full stop at the end of them.

Using the accent colour on hover:
![image](https://user-images.githubusercontent.com/26564949/84345123-d8bcb280-abef-11ea-9314-a5bcef034805.png)

Removal of the full stops:
![image](https://user-images.githubusercontent.com/26564949/84345218-1f121180-abf0-11ea-94c4-ee7b668b5671.png)

**Comment by Calinou** [comment]
@MHillier98 If you remove the `color: unset` property, it will use the red accent color like on your screenshot. I don't think it looks good in this context though, which is why I went for white instead.

We could remove the full stops as well, but I don't specially care about it either.

**Comment by MHillier98** [comment]
Agreed the white version looks better - I couldn't find any other examples of that particular button style, so I just wanted to ask :)
