### ISSUE TITLE
Request: Add the default themes to the forum

### ISSUE THREAD

**Issue by mariomadproductions** [godotengine/godot-website#764]
I'd like it if the default Discourse themes were available, as I don't really like the current theme (or dark themes generally). Others may appreciate the option too. I'm aware there may be a workaround in the form of CSS-modifying browser extensions, but this would work better.

This may be relevant: https://meta.discourse.org/t/allow-users-to-select-dark-or-light-theme/60857

**Comment by JohnVeness** [comment]
See https://github.com/godotengine/discourse-theme/issues/5

**Comment by mariomadproductions** [comment]
> See [godotengine/discourse-theme#5](https://github.com/godotengine/discourse-theme/issues/5)

Ah, I didn't see that, thanks. I'll close this issue.
