### ISSUE TITLE
Link on Godot download page to troubleshooting page in manual is broken

### ISSUE THREAD

**Issue by KratosPS** [godotengine/godot-website#773]
https://docs.godotengine.org/en/stable/about/troubleshooting.html

The link referenced on the Godot download page for troubleshooting install issues points to a page in the manual that does not exist. I'm unsure if its the case for the Windows or Linux installer page since I'm attempting to install on a Mac currently.
<img width="590" alt="Screenshot 2023-12-19 at 10 22 27 AM" src="https://github.com/godotengine/godot-docs/assets/15713342/bc84fb64-5897-4e38-b164-abdbf0f00fcf">
<img width="1437" alt="Screenshot 2023-12-19 at 10 22 44 AM" src="https://github.com/godotengine/godot-docs/assets/15713342/6daed21b-984b-4878-89a1-3fbe343d4610">

**Comment by JohnVeness** [comment]
Looks like the Troubleshooting page was moved from "about" to "tutorials", see https://github.com/godotengine/godot-docs/commit/bc2ff75da2d0252d91e6b18f6c3f14e42806980c . I'm not sure why the redirect isn't working, though?

**Comment by KratosPS** [comment]
I was able to find the troubleshooting page by searching, Just wanted to bring up the issue so it could get fixed eventually so new users have an easier time finding it.

**Comment by KratosPS** [comment]
Did not mean to close. I don't use github often.
