### ISSUE TITLE
C# MySqlConnector error on connection

### ISSUE THREAD

**Issue by Zamir7** [godotengine/godot-website#776]
C#, 4.2. Stable, when connecting to a database via MySqlConnector 2.3.1 on Windows it works flawlessly, but on Android it crashes with an error.
There is a feeling that the conflict is in the safety of Physics2DConstraintSolveIslands.
But again, there is no error on the Desktop and there is also no error in the .Net application on Android without Godot.

Here are the first lines of the error:

E 0:00:08:0044 :0 @ Interop+CryptoInitializer..cctor(): BUG: Unreferenced static string to 0: Physics2DConstraintSolveIslands
   <C++ source code>core/string/string_name.cpp:127 @ unref()
   <Stack trace>:0 @ Interop+CryptoInitializer..cctor()
                  :0 @ Interop+Crypto..cctor()
                  :0 @ int System.Security.Cryptography.HashProviderDispenser+OneShotHashProvider.HashData(string, System.ReadOnlySpan1[System.Byte], System.Span1[System.Byte])
                  :0 @ bool System.Security.Cryptography.SHA1.TryHashData(System.ReadOnlySpan1[System.Byte], System.Span1[System.Byte], System.Int32&)

:0 @ System.Byte[] MySqlConnector.Protocol.Serialization.AuthenticationUtility.HashPassword(System.ReadOnlySpan`1[System.Byte], string)
                  :0 @ System.Byte[] MySqlConnector.Protocol.Serialization.AuthenticationUtility.CreateAuthenticationResponse(System.ReadOnlySpan`1[System.Byte], string)
                  :0 @ MySqlConnector.Protocol.PayloadData MySqlConnector.Protocol.Payloads.HandshakeResponse41Payload.Create(MySqlConnector.Protocol.Payloads.InitialHandshakePayload, MySqlConnector.Core.ConnectionSettings, string, bool, MySqlConnector.Protocol.CharacterSet , System.Byte[])
                  :0 @ void MySqlConnector.Core.ServerSession+<ConnectAsync>d__98.MoveNext()
                  :0 @ void

**Comment by JohnVeness** [comment]
Hi. https://github.com/godotengine/godot-website/ is just about the Godot website. You're probably looking for https://github.com/godotengine/godot

**Comment by Zamir7** [comment]
Oh, sorry
