### ISSUE TITLE
Review metadata exposed by Godot pages (OG tags?)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-website#8]
I've noticed that we don't see to fully document the relevant metadata that various external websites would use to display our links. Not sure exactly how this should work but I bet you web guys know what this is about :)

Here are some examples of Godot links posted on various sites, and the apparent lack of descriptive info that they provide:

- On Discord: See how our blog links only show a small icon and no text
![image](https://user-images.githubusercontent.com/4701338/30742324-de12dc02-9f98-11e7-862a-af68231e2aa2.png)

- On Twitter: godotengine.org links appear as plain text instead of generating a preview
![image](https://user-images.githubusercontent.com/4701338/30742398-2958c88e-9f99-11e7-9bba-973b0f086c50.png)
![image](https://user-images.githubusercontent.com/4701338/30742452-5fc0a16c-9f99-11e7-9fe9-ee8da73004b5.png)

- On Facebook: It does a better job, but the debugger also raises various warnings about missing OG tags. Addressing those might fix it for Twitter, Discord, etc.
![image](https://user-images.githubusercontent.com/4701338/30742516-bbb5b3ea-9f99-11e7-9a15-2ecc16494f91.png)

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgodotengine.org%2Farticle%2Fwe-need-your-help-improve-our-documentation-system

**Comment by akien-mga** [comment]
It seems to have gotten worse (since the update?): https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fgodotengine.org%2Farticle%2Fgodot-3-renderer-design-explained

```
Provided og:image URL, https://godotengine.orghttps://godotengine.org/storage/app/uploads/public/59c/821/f4a/59c821f4a5e6c895938383.jpg was not a valid URL.
```

**Comment by pcvonz** [comment]
I addressed the og:image issue. Problem was on this [line](https://github.com/godotengine/website/blob/fd0612fe5b7b488ff3561a705f831f43d6f80b83/themes/godotengine/partials/head.htm#L17). I suppose that the update to the blog plugin or website made it so that `{{ post.featured_images[0].path }}` provides the full url.

**Comment by akien-mga** [comment]
It would be really nice to get this fixed ASAP, our blog posts are shared more and more and Twitter and it looks terrible that metadata is not available:
![image](https://user-images.githubusercontent.com/4701338/32144374-06af7aa8-bcb8-11e7-855d-c67226b99a5d.png)

**Comment by fleskesvor** [comment]
There's a lot of different "standards"  used to enrich sites with meta content, but here's a list of some it might be worth looking into:

- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
- http://fivefilters.org/
- site maps: https://support.google.com/webmasters/answer/183668?hl=en

Site maps have been around for ages, and is the easiest way to control which links search engines display. 

There's also a "new" standard which has tons of options for marking up content like company information, content categories, movies, recipes, etc., but at the moment, I don't remember what it's called.

**Comment by fleskesvor** [comment]
I was thinking of RDFa. This page has a list of some alternate formats: https://developers.google.com/custom-search/docs/structured_data

http://schema.org/ has a huge vocabulary for structured data, but that's probably not of interest for this purpose.

**Comment by akien-mga** [comment]
Thanks for those info @fleskesvor. I went quick and dirty and added Twitter Card metadata in the header of blog posts (a1ab588). Someone more experienced than me should have a look at harmonizing how we handle the different kinds of pages and make sure that we expose relevant metadata everywhere.

**Comment by fleskesvor** [comment]
It looks like Twitter supports the open graph protocol as well, which should have much broader support: http://ogp.me/

Twitter also has a test tool, which can be used to check if your cards look the way you want them to: https://cards-dev.twitter.com/validator

There's an example of mixing their own meta tags with the open graph protocol at the bottom of this page: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#opengraph

**Comment by brainsick** [comment]
I think I can help.  I don't have any first hand experience with October CMS but I've watched the [blog tutorial](https://octobercms.com/blog/post/building-a-blog-and-forum) and understand the basics.  I've perused the repository here and have a basic lay of the land.

~~To understand the markup required to correctly populate the OGP tags, I need to understand/see how the blog posts themselves are created/marked up.  To that end, is it possible to get a read-only account in the CMS system where the blog posts are being created?~~

~~Alternatively, I don't see the posts themselves in the repository, so I'm guessing they're sitting on disk on the server or in an operational database.  Is it possible to get a copy of the directory/contents for say the [Beta 2](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-2) article?~~

~~Maybe screenshots of all the screens/files you created/attached in the CMS to create the article?  It would help to see your side of the workflow.~~

Nevermind, clearly the basics are working as is evidenced here.

```
    <meta property="og:image" content="https://godotengine.org/storage/app/uploads/public/5a3/c39/918/5a3c399188781933894734.jpg" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@godotengine" />
    <meta name="twitter:title" content="Dev snapshot: Godot 3.0 beta 2" />
    <meta name="twitter:description" content="After three weeks of testing of the 3.0 beta 1 snapshot, we&#039;re now ready for a new beta release fixing many of the reported issues and then some! It also includes a surprise lightmapper from Juan, and many usability enhancements provided by our numerous contributors. The final 3.0 release is now very close, so stay tuned for more news and the release candidate!" />
    <meta name="twitter:image" content="https://godotengine.org/storage/app/uploads/public/5a3/c39/918/5a3c399188781933894734.jpg" />
```

The [link](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-2) does currently look good in Twitter.

![image](https://user-images.githubusercontent.com/1111573/34902482-dba034c8-f7e1-11e7-930c-baba6e51d2f5.png)

This is the same link in Riot.

![image](https://user-images.githubusercontent.com/1111573/34902481-cefb8a24-f7e1-11e7-9e05-ec51b4ced65f.png)

Same link in Discord.

![image](https://user-images.githubusercontent.com/1111573/34902517-8c89e770-f7e2-11e7-8215-e608dece9a3d.png)

I don't have Facebook, so can't compare there, but will assume that your screenshots are still accurate and that nothing's changed.

**Comment by akien-mga** [comment]
Fixed by #16.

**Comment by brainsick** [comment]
It's probably bad form to comment on a closed issue, but I just wanted to follow up and say thanks to @fleskesvor for the links and initial research.  They saved me some time.  :)

**Comment by fleskesvor** [comment]
@brainsick No, problem. :slightly_smiling_face: I've worked with SEO people before, so I had a good idea what to look for. Glad you were able to implement this properly.
