### ISSUE TITLE
Link to Linux desktop integration instructions

### ISSUE THREAD

**Issue by ghost** [godotengine/godot-website#802]
When installing Godot on Linux, I'd find it useful if the [Linux desktop integration instructions](https://docs.godotengine.org/en/stable/about/faq.html#linux) were linked somewhere on/near the Download page.

There's a link to the Troubleshooting part of the docs, but not this section.

For most other Linux applications, installation instructions automatically do this for you (add the app to your menu with icon, etc.). In Godot's case, I understand why there's no 'installer' per se, so having these instructions nearby would be handy so people know how to get a Godot item in their applications menu for example.

**Comment by computer-science-student** [comment]
Hi, I had this exact same problem!

I would like to submit a PR to update Godot’s website. Would someone please assign this issue to me? I will add your link to the Linux download page (see picture below), and I will write what this link is for.

![image](https://github.com/godotengine/godot-website/assets/81597927/8d3ad208-6a09-4d37-a14a-bf8ca3e9728c)

**Comment by Calinou** [comment]
> I would like to submit a PR to update Godot’s website. Would someone please assign this issue to me?

You can open a pull request right away 🙂 

For future reference, we only use the assignees feature for core contributors (and we don't always use it in the first place). Since contributors can leave at any time for any reason, we'd rather avoid a situation where nobody is working on an issue because it's assigned to someone who is no longer active.

**Comment by computer-science-student** [comment]
Thanks for getting back to me! I will do as you say.

**Comment by bits-by-brandon** [comment]
Can this be closed since https://github.com/godotengine/godot-website/pull/867 was merged?
