### ISSUE TITLE
Update the forum URL as godotdevelopers.org expired

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-website#81]
https://godotdevelopers.org has expired and should be replaced with the URL https://godotforums.org/.

**Edit:** I noticed after creating this issue that this will be solved by https://github.com/godotengine/godot-website/pull/80.

**Comment by Calinou** [comment]
I noticed after creating this issue that this will be solved by https://github.com/godotengine/godot-website/pull/80.

**Comment by MHillier98** [comment]
It seems like this has been updated again, as seen here [in this reddit thread](https://www.reddit.com/r/godot/comments/bi3hki/godotforums_the_new_and_improved_unofficial/).

[https://godotforums.org/](https://godotforums.org/) is the new forum.

**Comment by Calinou** [comment]
This was resolved in https://github.com/godotengine/godot-website/commit/081965602b9c96987ee8bf51efe200e527a0366e, closing.
