### ISSUE TITLE
Include Link List on Community Page

### ISSUE THREAD

**Issue by MurderVeggie** [godotengine/godot-website#819]
We made this overview (https://links.godotengine.org/) for easier sharing around social media and beyond, and currently use it in all our profile bios. 

I recon it would make sense to add it under the community tab of our website (https://godotengine.org/community/) as well, instead of listing all platforms seperately there. Helps to prevent redundancy issues in the future, too.

**Comment by adamscott** [comment]
How about something like this? A box like events, but for links. I'll rework the design if it pleases you.

![image](https://github.com/godotengine/godot-website/assets/270928/54d94cdc-30da-4e2a-948b-1c00d4c51a4b)
