### ISSUE TITLE
WebP is not PNG

### ISSUE THREAD

**Issue by JeremyStarTM** [godotengine/godot-website#824]
All PNG downloads on [the Press Kit site](https://godotengine.org/press/) link to WebP images.

I don't think that WebP and PNG are the same image format :)

**Comment by Calinou** [comment]
These were converted in https://github.com/godotengine/godot-website/pull/803.

I suggest putting the PNG versions back in for the press kit, as the press kit should be as universal as possible (while WebP images are not supported in every app out there).
