### ISSUE TITLE
Marking Custom Resources as New in 4.0 is confusing

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot-website#835]
See https://godotengine.org/features/

> ### Create data-driven elements with custom resources
>
> **New in 4.0:** Define scriptable objects called resources to describe characters, entities, and data structures in your game. Use your custom objects directly in the editor by assigning them to nodes. Resources come with a high-level API to store and read them, and they support every Godot type, including other resources.

This gives the impression that using custom resource is impossible before 4.0.

I think the improvement about custom resources in 4.0 is allowing specifying custom resources as an export variable type.

**Comment by coppolaemilio** [comment]
Fixed with https://github.com/godotengine/godot-website/commit/6ab2bbbe41fc7db109907f6d36f5531902b9079f

Thanks!
