### ISSUE TITLE
Add news subscription

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot-website#84]
**Issue description:**
Currently there is no way to make subscribe and receive news to email. It would be very nice to have this ability.

**Comment by Calinou** [comment]
There's an RSS feed at https://godotengine.org/rss.xml which you can add to any feed reader application, but I agree it should be made clearer somehow (it doesn't seem to be linked anywhere on the page).

**Comment by breakmt** [comment]
Wow, RSS, didn't know that. Actually, in my opinion and observation, **almost** no one uses it nowadays.

**Comment by MHillier98** [comment]
RSS is definitely still alive, and there a number of RSS to email services out there that you can use.

**Comment by breakmt** [comment]
Ok... At least button for RSS like Unity blog
![2019-04-23_120427](https://user-images.githubusercontent.com/1552169/56568734-46f37f80-65c0-11e9-8ee9-a4bc7ac48be8.png)

**Comment by MHillier98** [comment]
Agreed, didn't even realise it's not linked anywhere on the website

**Comment by voithos** [comment]
In addition to the RSS button, I'd like to strongly suggest that the site also provide an easier to use (and perhaps more common, nowadays) text-field with a big "Subscribe" button -- something like what this uses: https://changelog.com/.

It'd make it much easier for interested folks to keep up with the engine.
