### ISSUE TITLE
Add credit to featured games in feature screenshots

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot-website#886]
Hello!

I just realised that the screenshot used for the "simple and powerful 3D" does not credit the game featured (Human Diaspora). I had to do an image search on google to find it.

![image](https://github.com/user-attachments/assets/90e3ca2a-cd0c-498c-ad9a-6ca66b28c0fc)

**Comment by coppolaemilio** [comment]
Added a title tag with the name of the game: https://github.com/godotengine/godot-website/commit/1e049726684b117bd2c9e08e6f6886c1a899b07a

Thanks!
