### ISSUE TITLE
Make Donation Button visible on Mobile main page

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot-website#887]
Hello,

At the moment, the donation button is burried inside the menu button on the mobile main page. 
I am thinking that it might be good that for the donation button to be more visible/accessible; as its counterpart on the desktop webpage.

Here are different suggestions:
![image](https://github.com/user-attachments/assets/0e7b230c-5f07-47fe-9685-4e700097df01)

**Comment by G0lden07** [comment]
I like the third suggestion (The one on the left).
