### ISSUE TITLE
fund.godotengine.org Contribute button has a broken link

### ISSUE THREAD

**Issue by PZerua** [godotengine/godot-website#906]
Hi all and congrats for the new release!

Not exactly related to the main website, but I'm not sure the [fund webpage](https://fund.godotengine.org/) is open sourced (I couldn't find it at least). If you click in the Contribute button there, it points to: https://docs.godotengine.org/en/stable/contributing/ways_to_contribute.html (which does not exist) instead of https://docs.godotengine.org/en/stable/contributing/how_to_contribute.html.

**Comment by coppolaemilio** [comment]
Thanks! it should be fixed :)
