### ISSUE TITLE
Godot 4.3 Announcement page paragraphs are mushed together

### ISSUE THREAD

**Issue by glaucc** [godotengine/godot-website#908]
Link: [Link](https://godotengine.org/releases/4.3/)
The parahraphs aren't remotely readable. I would've fixed it myself but I don't have knowledge with Jekyll.
Thank you all for your efforts.

Windows 8, Firefox
![Cap222ture](https://github.com/user-attachments/assets/1b710f12-9dc5-4ff7-be6c-a2beab50cbb6)

**Comment by Calinou** [comment]
This is likely because you're on an old Firefox version (given you're on Windows 8), and the release page uses CSS features only present in very recent Firefox versions (Firefox 115 ESR also looks broken).

This will need some redesigning of the page to be fixed.

**Comment by adamscott** [comment]
~~Will not fix, unfortunately.~~ This is due to the page using extensively the `:has()` pseudo-selector.

**Comment by adamscott** [comment]
What I could do is to add rules to display flex if `:has()` is not supported. Will see tomorrow.

**Comment by glaucc** [comment]
Good man. It would be nice to be fixed, thanks for the effort.

**Comment by adamscott** [comment]
@coppolaemilio Our version of Sass is too old, it doesn't support `@supports selector()`. Ironic.

<img width="1052" alt="Capture d’écran, le 2024-08-19 à 09 47 34" src="https://github.com/user-attachments/assets/e99ff0bb-2d7d-408c-9532-7da8d39d30d6">

**Comment by coppolaemilio** [comment]
While the issue is not 100% solved, it should be better than the current version.
