### ISSUE TITLE
Website is broken when opened in Mobile with desktop mode 

### ISSUE THREAD

**Issue by kusaflow** [godotengine/godot-website#91]
**android, crome**

**Issue description:**
The website is not responsive at the section "THE GAME ENGINE YOU WAITED FOR." In mobile phone.

**Comment by Calinou** [comment]
Can you take a screenshot and upload it here, please?

Note that if you use desktop mode in a mobile browser, it's generally expected that websites will look broken somehow. That setting is only intended to be used on non-responsive websites.

**Comment by kusaflow** [comment]
yeah absolutely i understand that but i thought it is good to tell you about that :)

![Screenshot_20190802-175046_Chrome](https://user-images.githubusercontent.com/19837270/62369917-c04f2680-b54e-11e9-8504-b612b14b3fd9.jpg)

**Comment by MHillier98** [comment]
Looks like this could be fixed by removing ```height: 100%``` from that image when it's on mobile.
