### ISSUE TITLE
Showcase: platform icons issues

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#919]
Hello. I've been looking at https://godotengine.org/showcase/ and have a few suggestions.

Regarding the platform icons under each game image (Windows, macOS, Xbox, Switch etc.):

![image](https://github.com/user-attachments/assets/09240959-d51e-4a27-a182-c2a1bb8df371)

1, The Switch and Xbox ones are a little "busy" with the text underneath, when viewed at small sizes, especially the Switch one. Could the text on those two be removed, making the icons just the logos, so they look more consistent when side-by-side?

2, Could the sizing be checked so that they are more equal in height? Some look bigger than others. This would be easier to check if 1 is done.

3, Is there a better icon that could be researched and used for "web"? I know the "5 in a shield" means HTML5, but is that the best or most appropriate icon now?

4, A minor thing, but when hovering over the icons, the tooltip text that comes up is all lowercase, e.g. "xbox", "playstation", "macos" - could it instead be "Xbox", "PlayStation", "macOS" etc.?

Thanks for reading!

**Comment by bits-by-brandon** [comment]
Removes the wordmark from some logos:
https://github.com/godotengine/godot-website/pull/948

**Comment by coppolaemilio** [comment]
The only one left is iOS, right? I don't know if there is an icon for it 🤔

**Comment by Calinou** [comment]
> The only one left is iOS, right? I don't know if there is an icon for it 🤔

The iOS logo is usually just the iOS wordmark, since an Apple logo is ambiguous. The Apple logo is generally understood to refer to macOS, however, if it's right next to an Android logo, it may be interpreted as iOS instead.

**Comment by coppolaemilio** [comment]
I guess we can close this one then. Thank you everyone!
