### ISSUE TITLE
Showcase: Put game title in text too

### ISSUE THREAD

**Issue by JohnVeness** [godotengine/godot-website#921]
Hi again. On https://godotengine.org/showcase/ currently the game titles are only in the thumbnail graphic. Some of them can be tricky to read quickly (not necessarily picking on the ones below!), and you can't use Ctrl+F to search for the titles.

![image](https://github.com/user-attachments/assets/40e85794-4cd3-4277-875a-5a047f17a069)

So, could the game title appear under the thumbnail along with the developer name, e.g.:

Madness/Endless
by Poke the Ant

A Most Extraordinary Gnome
by Save Sloth Studios

Endoparasitic
by Miziziziz

Dome Keeper
by Bippinbits

Adding the word "by" also make it clearer the name after it is of the developer, not the name of the game, which is not immediately obvious on the current site.

**Comment by Calinou** [comment]
I'm not sure where we could fit the title in an elegant way. This is with a quick change to put the title outside of the caption (as the caption's items are displayed on a single line using flexbox):

![image](https://github.com/user-attachments/assets/2c2cc3fc-542d-423d-b83c-fdcb7832ef51)

We'll need a second line in any case, as we don't have enough space to fit the title, platforms *and* author on the same line.

**Comment by JohnVeness** [comment]
Thanks for looking into this.

I don't know how you could implement this, but as at least some of the platform icons (see also #919) are quite tall, I would hope that that two lines of text next to them would fit quite well. E.g. something like:

![image](https://github.com/user-attachments/assets/f208c018-fdb5-419b-84b7-7665b4271a56)

(Possibly with "by" in front of the developer name, or some other way of distinguishing the game name from the developer name, e.g. using bold).

**Comment by JohnVeness** [comment]
Actually, it would probably look better (at least in languages that use left-to-right text) to have the game name and developer name on the left, and the platform icons on the right (forgive my bad image editing - the idea is that the two rows of text would be roughly the same height as the single row of icons).

![image](https://github.com/user-attachments/assets/3c03d423-81ab-4290-824d-89cd955df6be)

**Comment by bits-by-brandon** [comment]
My suggestion to tweak these cards:

Bold the title for visual hierarchy
Make the icons and text be centered with `align-items: center`
reduce size of icons
Make all text `--primary-color-text`
Slightly reduce border radius to 4px
Remove the left and right margins on the content

<img width="334" alt="Screenshot 2024-10-17 at 8 17 57 AM" src="https://github.com/user-attachments/assets/821f94ca-768a-4796-87b7-3c60649e3720">

**Comment by coppolaemilio** [comment]
@bits-by-brandon do you want to make the PR with the update? I really like your proposal

**Comment by bits-by-brandon** [comment]
@coppolaemilio okay. Only because you asked so nicely 😄

**Comment by bits-by-brandon** [comment]
See pr created here
https://github.com/godotengine/godot-website/pull/947
