### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by KellyThomas** [godotengine/godot-website#941]
https://godotengine.org/community/

1. On the community page the second item under the official communities heading is labeled "Discord".

![chrome_screenshot_2 Oct 2024 11_07_41 am AWST](https://github.com/user-attachments/assets/2f9b5eea-00e3-40a1-8d1a-c2051ce5007d)

2. When I follow that link I see a message saying the invite may have expired.

![Screenshot_20241002-110810-700](https://github.com/user-attachments/assets/c595a422-f4fb-43f8-bef4-9b4899d0ad46)

**Comment by coppolaemilio** [comment]
The Discord invite is currently disable because we were getting raided. It will go back to normal whenever the attack stops. Closing the issue now but feel free to reply if you need anything else. Cheers!

**Comment by ghost** [comment]
Is this still a problem? 
The link is still invalid as-of Dec 1st ... 

Maybe not enough boosts? Someone suggested to me that is a possibility too. 
(Which if that is used as a hard-coded link on the site and in-docs, the foundation should probably allot money for it to always be boosted enough to assure that tier lol)

**Comment by ghost** [comment]
Link is fixed, appears lack of boosts was in-fact the issue, which caused temporarily lose of the vanity url for discord.gg/godotengine. 

Still think it'd be good if the foundation allot a fund (and eye on it) to assure this was a nonissue going forward.
