### ISSUE TITLE
Patreon widget is no longer shown in the menu bar

### ISSUE THREAD

**Issue by anissen** [godotengine/godot-website#95]
**Operating system, Browser, Browser Version:**
MacOS 10.14
Google Chrome 76

**Issue description:**

I would expect the Patreon widget to be visible in the menu bar as usual, but that's not the case.

**Screenshots (greatly appreciated if it’s a style issue)**
![image](https://user-images.githubusercontent.com/879967/64046218-a879bb00-cb6b-11e9-8539-166077fa9782.png)

**Comment by akien-mga** [comment]
Fixed. Not sure how, last time I tried it was still broken but today everything works fine. I guess our hosting provider fixed the issue they had where `php-curl` could not be installed both in php5 and php7 variants (both are now installed).
