### ISSUE TITLE
Navigation bar not set to sticky

### ISSUE THREAD

**Issue by adfriz** [godotengine/godot-website#965]
I have noticed that the navigation bar not set to sticky, I suggest change it to sticky for improving user experience and easier navigation.

https://github.com/user-attachments/assets/35cbe618-8a74-4d68-8d95-1fbaacc56a04

there's also additional suggestion for adding a button that fixed on the bottom right for easier jump to top instead scrolling manually.

**Comment by coppolaemilio** [comment]
This was decided to not be preferable back then: https://github.com/godotengine/godot-website/pull/406

I honestly did it out of habit, but not having it haven't bothered me really.

**Comment by Calinou** [comment]
> there's also additional suggestion for adding a button that fixed on the bottom right for easier jump to top instead scrolling manually.

Like fixed navigation bars, this is also considered an antifeature nowadays as the keyboard's <kbd>Home</kbd> button achieves the same function in an universal manner. (On iOS, you can also tap the browser's title bar.)
